🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/check-for-updates b/bin/check-for-updates
--- a/bin/check-for-updates
+++ b/bin/check-for-updates
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-APPNAME="$(basename "$0")"
+PROG="$(basename "$0")"
+VERSION="202103230834-git"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
@@ -8,112 +9,194 @@ SRC_DIR="${BASH_SOURCE%/*}"
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 202103200617-git
+##@Version       : 202103230834-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
 # @License       : WTFPL
 # @ReadME        : check-for-updates --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Saturday, Mar 20, 2021 06:17 EDT
+# @Created       : Tuesday, Mar 23, 2021 08:34 EDT
 # @File          : check-for-updates
-# @Description   : Check for package updates
-# @TODO          : Add brew/choco support
+# @Description   : check for package updates
+# @TODO          :
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Import functions
-CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
-SCRIPTSFUNCTDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}/functions"
-SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-testing.bash}"
-SCRIPTSFUNCTURL="${SCRIPTSAPPFUNCTURL:-https://github.com/dfmgr/installer/raw/master/functions}"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [ -f "$PWD/$SCRIPTSFUNCTFILE" ]; then
-  . "$PWD/$SCRIPTSFUNCTFILE"
-elif [ -f "$SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE" ]; then
-  . "$SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE"
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
 else
-  echo "Can not load the functions file: $SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE" 1>&2
-  exit 1
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# user system devenv dfmgr dockermgr fontmgr iconmgr pkmgr systemmgr thememgr wallpapermgr
-user_install
-__options "$@"
+# helper functions - See github.com/dfmgr/misc/bin/functions.bash
+__version() { app_version; }
+__ask_me_to_update() { ask_yes_no_question "Would you like to update" "pkmgr silent upgrade"; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [ -f "/usr/local/bin/dmenupass" ]; then
-  SUDO_ASKPASS="/usr/local/bin/dmenupass}"
-fi
+__help() {
+  app_help "4" "Usage: check-for-updates" \
+    "-c, --config           -  create config file" \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help" \
+    "--options              -  used by completions"
+  exit $?
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-updatemess="You have updates available \nWould you like to update now?"
-xmessageopts="-nearmouse -timeout 10 -geometry 500x200 -center"
-notifications="${UPDATE_NOTIFY:-yes}"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-[ -d "${TMPDIR:-$HOME/.local/tmp}" ] || __mkd "${TMPDIR:-$HOME/.local/tmp}"
-[ -f "${TMPDIR:-$HOME/.local/tmp}/update_check" ] || __rm_rf "${TMPDIR:-$HOME/.local/tmp}/update_check"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if ! __am_i_online; then
-  echo "0"
-  echo "$updates" >"$HOME/.local/tmp/update_check"
-  exit
-fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Arch update check
-if [ -f /usr/bin/pacman ]; then
-  if ! updates_arch=$(pacman -Qu 2>/dev/null | wc -l); then
-    updates_arch=0
+__gen_config() {
+  printf_green "Generating the config file in"
+  printf_green "$CHECK_FOR_UPDATES_CONFIG_DIR/$CHECK_FOR_UPDATES_CONFIG_FILE"
+  [ -d "$CHECK_FOR_UPDATES_CONFIG_DIR" ] || mkdir -p "$CHECK_FOR_UPDATES_CONFIG_DIR"
+  [ -d "$CHECK_FOR_UPDATES_CONFIG_BACKUP_DIR" ] || mkdir -p "$CHECK_FOR_UPDATES_CONFIG_BACKUP_DIR"
+  [ -f "$CHECK_FOR_UPDATES_CONFIG_DIR/$CHECK_FOR_UPDATES_CONFIG_FILE" ] &&
+    cp -Rf "$CHECK_FOR_UPDATES_CONFIG_DIR/$CHECK_FOR_UPDATES_CONFIG_FILE" "$CHECK_FOR_UPDATES_CONFIG_BACKUP_DIR/$CHECK_FOR_UPDATES_CONFIG_FILE.$$"
+  cat <<EOF >"$CHECK_FOR_UPDATES_CONFIG_DIR/$CHECK_FOR_UPDATES_CONFIG_FILE"
+# Settings for check-for-updates
+CHECK_FOR_UPDATES_CACHEDIR="\${CACHE_DIR:-$HOME/.cache/check_all_updates_sh}"
+CHECK_FOR_UPDATES_ENABLE_NOTIFICATIONS="\${CHECK_FOR_UPDATES_ENABLE_NOTIFICATIONS:-yes}"
+CHECK_FOR_UPDATES_ENABLE_UPDATE_NAG="\${CHECK_FOR_UPDATES_ENABLE_UPDATE_NAG:-yes}"
+CHECK_FOR_UPDATES_SUDO_ASKPASS_PROGRAM="\${SUDO_ASKPASS:-/usr/local/bin/dmenupass}"
+__ask_me_to_update() { ask_yes_no_question "Would you like to update" "pkmgr silent upgrade"; }
+
+EOF
+  if [ -f "$CHECK_FOR_UPDATES_CONFIG_DIR/$CHECK_FOR_UPDATES_CONFIG_FILE" ]; then
+    printf_green "Your config file for check-for-updates has been created"
+    true
+  else
+    printf_red "Failed to create the config file"
+    false
   fi
-  # yay doesn't do sudo
-  if [ -f /usr/bin/yay ]; then
-    if ! updates_aur=$(yay -Qum 2>/dev/null | wc -l); then
-      updates_aur=0
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Defaults
+exitCode=
+CHECK_FOR_UPDATES_CONFIG_FILE="settings.conf"
+CHECK_FOR_UPDATES_CONFIG_DIR="$HOME/.config/myscripts/check-for-updates"
+CHECK_FOR_UPDATES_CONFIG_BACKUP_DIR="$HOME/.local/share/myscripts/check-for-updates/backups"
+CHECK_FOR_UPDATES_OPTIONS_DIR="$HOME/.local/share/myscripts/check-for-updates/options"
+CHECK_FOR_UPDATES_CACHEDIR="${CACHE_DIR:-$HOME/.cache/check_all_updates_sh}"
+CHECK_FOR_UPDATES_ENABLE_NOTIFICATIONS="${CHECK_FOR_UPDATES_ENABLE_NOTIFICATIONS:-yes}"
+CHECK_FOR_UPDATES_ENABLE_UPDATE_NAG="${CHECK_FOR_UPDATES_ENABLE_UPDATE_NAG:-yes}"
+CHECK_FOR_UPDATES_SUDO_ASKPASS_PROGRAM="${SUDO_ASKPASS:-/usr/local/bin/dmenupass}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Argument/Option settings
+SETARGS="${*}"
+SHORTOPTS="c,v,h"
+LONGOPTS="options,config,version,help"
+ARRAY=""
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Generate Files
+[ -f "$CHECK_FOR_UPDATES_CONFIG_DIR/$CHECK_FOR_UPDATES_CONFIG_FILE" ] || __gen_config &>/dev/null
+[ -f "$CHECK_FOR_UPDATES_OPTIONS_DIR/options" ] || __list_options "$CHECK_FOR_UPDATES_OPTIONS_DIR" &>/dev/null
+[ -f "$CHECK_FOR_UPDATES_OPTIONS_DIR/array" ] || __list_array "$CHECK_FOR_UPDATES_OPTIONS_DIR" "$ARRAY" &>/dev/null
+[ -d "$CHECK_FOR_UPDATES_CACHEDIR" ] || mkdir -p "$CHECK_FOR_UPDATES_CACHEDIR"
+[ -f "$CHECK_FOR_UPDATES_CACHEDIR/update_check" ] || rm -Rf "$CHECK_FOR_UPDATES_CACHEDIR/update_check"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Import config
+[ -f "$CHECK_FOR_UPDATES_CONFIG_DIR/$CHECK_FOR_UPDATES_CONFIG_FILE" ] &&
+  . "$CHECK_FOR_UPDATES_CONFIG_DIR/$CHECK_FOR_UPDATES_CONFIG_FILE"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+SUDO_ASKPASS="$CHECK_FOR_UPDATES_SUDO_ASKPASS_PROGRAM"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# options
+setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -n "$PROG" -- "$@" 2>/dev/null)
+eval set -- "$setopts" 2>/dev/null
+while :; do
+  case $1 in
+  --options)
+    __list_options "$CHECK_FOR_UPDATES_OPTIONS_DIR"
+    __list_array "$CHECK_FOR_UPDATES_OPTIONS_DIR" "$ARRAY"
+    exit $?
+    ;;
+  -v | --version)
+    __version
+    exit $?
+    ;;
+  -h | --help)
+    __help
+    exit $?
+    ;;
+  -c | --config)
+    __gen_config
+    exit $?
+    ;;
+  --)
+    shift 1
+    break
+    ;;
+    #*) break ;;
+  esac
+  shift
+done
+set -- "$SETARGS"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Check for required applications
+cmd_exists --error bash || exit 1
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# begin main app
+if am_i_online; then
+  #Arch update check
+  if [ -f /usr/bin/pacman ]; then
+    if ! updates_arch=$(pacman -Qu 2>/dev/null | wc -l); then
+      updates_arch=0
+      updates="$updates_arch"
     fi
-  fi
-  updates=$(("$updates_arch" + "$updates_aur"))
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Debian/Ubuntu update check
-elif [ -f /usr/bin/apt ]; then
-  if ! updates=$(sudo apt-get update >/dev/null && apt-get --just-print upgrade | grep "Inst " | wc -l); then
-    updates=0
-  fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Fedora/RedHat/CentOS
-elif [ -f /usr/bin/dnf ]; then
-  if ! updates=$(sudo dnf check-update -q | grep -v Security | wc -l); then
-    updates=0
-  fi
-elif [ -f /usr/bin/yum ]; then
-  if ! updates=$(sudo yum check-update -q | grep -v Security | wc -l); then
-    updates=0
-  fi
-fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [ "$updates" -gt 0 ]; then
-  echo " $updates"
-else
-  echo "0"
-  rm -Rf "$HOME/.local/tmp/update_check"
-  exit 0
-fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-#if [ ! -f "$HOME/.cache/update_nag" ] && [ -n "$DISPLAY" ]; then
-#DISPLAY=$DISPLAY xmessage -buttons Yes:0,No:1 -default Yes $xmessageopts --title "You have updates" "$updatemess" && \
-#sleep 20 && #pkmgr silent update && \
-#DISPLAY=$DISPLAY xmessage -buttons OK:0 -default Ok $xmessageopts --title "Done updating" "Update completed successfuly" && \
-#sleep 20
-#DISPLAY=$DISPLAY xmessage -buttons Yes:0,No:1 -default Yes $xmessageopts --title "message" "Show this again?" && \
-#sleep 20 ; ret=$? ; if [ "$ret" -ne 0 ]; then touch $HOME/.cache/update_nag ; fi
-#fi
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-echo "$updates" >"$HOME/.local/tmp/update_check"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [[ "$1" =~ notify ]] || [ "$UPDATE_NOTIFY" = "yes" ]; then
-  if [ "$updates" -gt 0 ]; then
-    if [ -f /usr/local/bin/notifications ]; then
-      if [ ! -f "$HOME/.local/tmp/update_check" ]; then
-        /usr/local/bin/notifications "System Updates:" "You have $updates update[s] avaliable"
+    #yay doesn't do sudo
+    if [ -f /usr/bin/yay ]; then
+      if ! updates_aur=$(sudo --user $USER yay -Qum 2>/dev/null | wc -l); then
+        updates_aur=0
       fi
     fi
+    updates=$(("$updates_arch" + "$updates_aur"))
+  #Debian update check
+  elif [ -f /usr/bin/apt ]; then
+    if ! updates=$(sudo apt-get update >/dev/null && apt-get --just-print upgrade | grep "Inst " | wc -l); then
+      updates=0
+    fi
+
+  elif [ -f /usr/bin/dnf ]; then
+    if ! updates=$(sudo dnf check-update -q | grep -v Security | wc -l); then
+      updates=0
+    fi
+
+  elif [ -f /usr/bin/yum ]; then
+    if ! updates=$(sudo yum check-update -q | grep -v Security | wc -l); then
+      updates=0
+    fi
   fi
+else
+  updates=0
+fi
+if [[ $updates -gt 0 ]]; then
+  echo "$updates"
+else
+  echo 0
+  rm -Rf "$CHECK_FOR_UPDATES_CACHEDIR/update_check"
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# end
+if [ "$CHECK_FOR_UPDATES_ENABLE_UPDATE_NAG" = "yes" ] && [[ "$updates" -gt 0 ]]; then
+  __ask_me_to_update
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+if [[ $updates -gt 0 ]]; then
+  if [ "$CHECK_FOR_UPDATES_ENABLE_NOTIFICATIONS" = "yes" ]; then
+    if [ ! -f "$CHECK_FOR_UPDATES_CACHEDIR/update_check" ]; then
+      echo "$updates" >"$CHECK_FOR_UPDATES_CACHEDIR/update_check"
+      /usr/local/bin/notifications "System Updates:" "You have $updates update[s] avaliable"
+    fi
+  fi
+fi
+
+# lets exit with code
+exit "${exitCode:-$?}"
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# execute function
+check-for-updates_main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# End application
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
