🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/gen-nginx b/bin/gen-nginx
--- a/bin/gen-nginx
+++ b/bin/gen-nginx
@@ -1,104 +1,85 @@
 #!/usr/bin/env bash
 
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="gen-nginx"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version     : 022420211808-git
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : gen-nginx
-# @Created     : Wed, Aug 05, 2020, 02:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Generate a nginx proxy host
-# @Source      :
-#
+#set opts
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-# Set functions
-
+##@Version       : 031220212322-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : gen-nginx --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Friday, Mar 12, 2021 23:22 EST
+# @File          : gen-nginx
+# @Description   : Generate a nginx proxy host
+# @TODO          :
+# @Other         :
+# @Resource      :
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Import functions
+CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
+SCRIPTSFUNCTDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}/functions"
+SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-testing.bash}"
 SCRIPTSFUNCTURL="${SCRIPTSAPPFUNCTURL:-https://github.com/dfmgr/installer/raw/master/functions}"
-SCRIPTSFUNCTDIR="${SCRIPTSAPPFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}"
-SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-applications.bash}"
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-if [ -f "$PWD/functions/$SCRIPTSFUNCTFILE" ]; then
-  . "$PWD/functions/$SCRIPTSFUNCTFILE"
-elif [ -f "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE" ]; then
-  . "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE"
+if [ -f "$PWD/$SCRIPTSFUNCTFILE" ]; then
+  . "$PWD/$SCRIPTSFUNCTFILE"
+elif [ -f "$SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE" ]; then
+  . "$SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE"
+else
+  echo "Can not load the functions file: $SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE" 1>&2
+  exit 1
 fi
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-systemmgr_install
+# user system devenv dfmgr dockermgr fontmgr iconmgr pkmgr systemmgr thememgr wallpapermgr
+user_install
 __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-# Set functions
-
-SCRIPTSFUNCTURL="${SCRIPTSAPPFUNCTURL:-https://github.com/dfmgr/installer/raw/master/functions}"
-SCRIPTSFUNCTDIR="${SCRIPTSAPPFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}"
-SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-applications.bash}"
-
+__requiresudo true
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-if [ -f "$PWD/functions/$SCRIPTSFUNCTFILE" ]; then
-  . "$PWD/functions/$SCRIPTSFUNCTFILE"
-elif [ -f "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE" ]; then
-  . "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE"
-fi
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-systemmgr_install
-__options "$@"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-if [[ $(id -u) -ne 0 ]]; then
-  printf_exit "Please re-run this as root"
-  exit
-fi
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
 __nginx_confdir() {
   if [ -d /etc/nginx/sites-enabled ]; then
     nginxconfdir="/etc/nginx/sites-enabled"
   elif [ -d "/etc/nginx/vhosts.d" ]; then
-    nginxconfdir="/etc/nginx/conf/vhosts.d"
+    nginxconfdir="/etc/nginx/vhosts.d"
   else
-    printf_custom_question "Where are your nginx server files located? "
-    read -r nginxconfdir && echo
+    printf_read_question_nt "4" "Where are your nginx server files located?" "120" "nginxconfdir" "-e"
     if [[ ! -d "$nginxconfdir" ]]; then
       printf_exit "$nginxconfdir is an invalid directory"
       exit 1
     fi
   fi
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-__nginx_dom() {
-  printf_custom_question "What is your domain name?"
-  read -r NGINXDOMAIN && echo
-  printf_custom_question "What is the name of the app?"
-  read -r REVPROXYNAME && echo
-  printf_custom_question "What should I proxy for?" [localhost]
-  read -r REVPROXY && echo
-  printf_custom_question "What is your APPs port?" [3000]
-  read -r REVPROXY_PORT && echo
-  printf_custom_question "What is the protocol http[s]?" [http]
-  read -r REVPROXY_PROTO && echo
-
+__hosts() {
+  grep "$REVPROXY" /etc/hosts &>/dev/null || echo "127.0.0.3      $REVPROXY" | sudo tee -a /etc/hosts &>/dev/null
+  grep "$NGINXDOMAIN" /etc/hosts &>/dev/null || echo "127.0.0.3      $NGINXDOMAIN" | sudo tee -a /etc/hosts &>/dev/null
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
+__nginx_dom() {
+  printf_read_question_nt "4" "What is your domain name?" "120" "NGINXDOMAIN" "-e -i $(hostname -f) "
+  printf_read_question_nt "4" "What is the name of the app?" "120" "REVPROXYNAME" "-e "
+  printf_read_question_nt "4" "What should I proxy for?" "120" "REVPROXY" "-e -i localhost "
+  printf_read_question_nt "4" "What is your APPs port [3000]?" "120" "REVPROXY_PORT" "-e -i 3000 "
+  printf_read_question_nt "4" "What is the protocol http[s]?" "120" "REVPROXY_PROTO" "-e -i http"
+  [ -n "$NGINXDOMAIN" ] && NGINXDOMAIN="$NGINXDOMAIN" || printf_exit "domain name is required"
+  [ -n "$REVPROXYNAME" ] && REVPROXYNAME="$REVPROXYNAME" || printf_exit "app name is required"
+  REVPROXY="${REVPROXY:-localhost}"
+  REVPROXY_PORT="${REVPROXY_PORT:-3000}"
+  REVPROXY_PROTO="${REVPROXY_PROTO:-http}"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __nginx_conf() {
-  if [ -d /etc/letsencrypt/live/domain ] || [ -d /etc/letsencrypt/live/$(hostname -f) ]; then
-    cat <<EOF >$nginxconfdir/$NGINXDOMAIN.conf
-#Define your primary service
-#  upstream $REVPROXYNAME { server REVPROXY:$REVPROXY_PORT fail_timeout=0; }
+  if [ -d "/etc/letsencrypt/live/domain" ] || [ -d "/etc/letsencrypt/live/$(hostname -f)" ]; then
+    echo '#Define your primary service
+# upstream '$REVPROXYNAME' { server '$REVPROXY':'$REVPROXY_PORT' fail_timeout=0; }
 
 server {
   listen 443 ssl http2;
@@ -108,7 +89,7 @@ server {
   ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
   ssl_session_timeout 1d;
   ssl_session_cache shared:SSL:50m;
-  server_name $NGINXDOMAIN;
+  server_name '$NGINXDOMAIN';
   access_log /var/log/nginx/access.log;
   error_log  /var/log/nginx/error.log info;
   keepalive_timeout 75 75;
@@ -118,7 +99,7 @@ server {
 
   location / {
     proxy_redirect          http:// https://;
-    proxy_pass              $REVPROXY_PROTO://$REVPROXY;
+    proxy_pass              '$REVPROXY_PROTO://$REVPROXY';
     proxy_ssl_verify        off;
     send_timeout            3600;
     client_max_body_size    1024M;
@@ -156,11 +137,10 @@ server {
     include /etc/nginx/global.d/vnstats.conf;
     include /etc/nginx/global.d/others.conf;
 }
-EOF
+' | sudo tee "$nginxconfdir/$NGINXDOMAIN.conf" &>/dev/null
   else
-    cat <<EOF >$nginxconfdir/$NGINXDOMAIN.conf
-#Define your primary service
-#  upstream $REVPROXYNAME { server REVPROXY:$REVPROXY_PORT fail_timeout=0; }
+    echo '#Define your primary service
+# upstream '$REVPROXYNAME' { server '$REVPROXY':'$REVPROXY_PORT' fail_timeout=0; }
 
 server {
   listen 443 ssl http2;
@@ -170,7 +150,7 @@ server {
   ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
   ssl_session_timeout 1d;
   ssl_session_cache shared:SSL:50m;
-  server_name $NGINXDOMAIN;
+  server_name '$NGINXDOMAIN';
   access_log /var/log/nginx/access.log;
   error_log  /var/log/nginx/error.log info;
   keepalive_timeout 75 75;
@@ -180,7 +160,7 @@ server {
 
   location / {
     proxy_redirect          http:// https://;
-    proxy_pass              $REVPROXY_PROTO://$REVPROXY;
+    proxy_pass              '$REVPROXY_PROTO'://'$REVPROXY';
     proxy_ssl_verify        off;
     send_timeout            3600;
     client_max_body_size    1024M;
@@ -218,40 +198,28 @@ server {
     include /etc/nginx/global.d/vnstats.conf;
     include /etc/nginx/global.d/others.conf;
 }
-EOF
+' | sudo tee "$nginxconfdir/$NGINXDOMAIN.conf" &>/dev/null
+  fi
+  if [ -f "$nginxconfdir/$NGINXDOMAIN.conf" ]; then
+    printf_green "Successfully created $nginxconfdir/$NGINXDOMAIN.conf"
+  else
+    print_error "Failed to create $nginxconfdir/$NGINXDOMAIN.conf"
   fi
 }
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-NGINXDOMAIN="${NGINXDOMAIN:-$1}"
-REVPROXYNAME="${REVPROXYNAME:-$2}"
-REVPROXY="${REVPROXY:-$3}"
-REVPROXY_PORT="${REVPROXY_PORT:-$4}"
-REVPROXY_PROTO="${REVPROXY_PROTO:-$5}"
-
-if [ -z "$nginxconfdir" ]; then
-  __nginx_confdir
-fi
-
-if [ -z "$NGINXDOMAIN" ]; then
-  __nginx_dom
-fi
-
+main() {
+  NGINXDOMAIN="${NGINXDOMAIN:-$1}"
+  REVPROXYNAME="${REVPROXYNAME:-$2}"
+  REVPROXY="${REVPROXY:-$3}"
+  REVPROXY_PORT="${REVPROXY_PORT:-$4}"
+  REVPROXY_PROTO="${REVPROXY_PROTO:-$5}"
+  [ -z "$nginxconfdir" ] && __nginx_confdir
+  [ -z "$NGINXDOMAIN" ] && __nginx_dom
+  __nginx_conf "$@"
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-__nginx_conf
-
-if [ -n "$(grep $REVPROXY /etc/hosts 2>/dev/null)" ]; then
-  echo "127.0.0.1      $REVPROXY" >>/etc/hosts
-fi
-
-if [ -n "$(grep $NGINXDOMAIN /etc/hosts 2>/dev/null)" ]; then
-  echo "127.0.0.1      $NGINXDOMAIN" >>/etc/hosts
-fi
-
-printf_green "Setting up $NGINXDOMAIN for $REVPROXYNAME on port: $REVPROXY_PORT"
-
+main "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #End
