🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/gitadmin b/bin/gitadmin
--- a/bin/gitadmin
+++ b/bin/gitadmin
@@ -36,7 +36,6 @@ if [ -d "$1" ]; then
   shift 1
 elif [ "$1" = "-d" ] || [ "$1" = "-dir" ] || [ "$1" = "--dir" ]; then
   gitdir="$2"
-  __mkd "$gitdir"
   shift 2
   [ -d "$gitdir" ] || printf_exit "$gitdir doesn't seem to be a directory"
 else
@@ -69,7 +68,26 @@ if [ "$(git config --get user.email | wc -m)" -lt 2 ]; then
   printf_read_question "What is you Email" "120" "EMAIL"
   git config --global user.email "$EMAIl" 2>/dev/null
 fi
-
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__curl() { curl -q; }
+__curl_api_header() { curl -q; }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__git_pull() {
+  local dir="$1" && shift 1
+  local args="$*"
+  if [[ "$(git -C "$dir" pull $args -f -q)" != "fatal:" ]]; then return 0; else return 1; fi
+}
+__git_push() {
+  local dir="$1" && shift 1
+  local args="$*"
+  if [[ "$(git -C "$dir" push $args -q)" != "fatal:" ]]; then return 0; else return 1; fi
+}
+__git_clone() {
+  local url="$1" && shift 1
+  local dir="$1" && shift 1
+  local args="$*"
+  if [[ "$(git clone "$url" "$dir" -q $args)" != "fatal:" ]]; then return 0; else return 1; fi
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Creates a README.md file if one doesn't exist
 create_new_readme_template() {
@@ -252,8 +270,8 @@ run_git_setup_automated() {
     if [ -f "${REPODIR}/gitmasterconfig" ]; then cp -Rf "${REPODIR}/gitmasterconfig" "${REPODIR}/.git/config"; fi &&
     __devnull git -C "${REPODIR}" add . &&
     git -C "${REPODIR}" commit -q -m ' 🦈🏠🐜❗ Initial Commit ❗🐜🦈🏠 ' &&
-    __devnull git -C "${REPODIR}" push -q --set-upstream origin master -f &&
-    __devnull git -C "${REPODIR}" push -q -f &&
+    __devnull __git_push "${REPODIR}" --set-upstream origin master &&
+    __devnull __git_push "${REPODIR}" &&
     printf_green "Successfully pushed to: $PREVREPO" ||
     printf_red "Push to $PREVREPO has failed"
   echo ""
@@ -263,9 +281,9 @@ run_git_setup_automated() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Makes a new jeckyll site
 make_newsite() {
-  git -C "$HOME/Public/sites/$1" clone https://github.com/casjay-templates/domain-template &&
+  __git_clone https://github.com/casjay-templates/domain-template "$HOME/Public/sites/$1" &&
     rm -Rf "$HOME/Public/sites/new/.git" && cd "$HOME/Public/sites/$1" && "$EDITOR" _config.yml || return 1
-  git setup "${REPODIR}"
+  gitadmin "${REPODIR}" setup
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -299,7 +317,7 @@ git_init() {
   if [ -f "$REPODIR/gitmasterconfig" ]; then cp -Rf "$REPODIR/gitmasterconfig" "$REPODIR/.git/config"; fi
   git -C "$REPODIR" commit -m ' 🦈🏠🐜 Initial Commit 🐜🦈🏠 '
   git -C "$REPODIR" remote add origin "https://github.com/$1/$2"
-  git -C "$REPODIR" push -u origin master
+  __git_push "$REPODIR" -u origin master
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -370,7 +388,7 @@ ghcreate() {
 ghsinglerepo() {
   [ "$1" = "" ] && printf_red "Usage: --single userName repoName" && return 1
   [ "$2" = "" ] && printf_red "Usage: --create userName repoName Description" && return 1
-  git clone -q "https://github.com/$1/$2"
+  __git_clone "https://github.com/$1/$2" "${3:-}"
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -391,13 +409,13 @@ main() {
       SUCCES="Git pull $USERNAME/$i completed"
       printf_purple "Now running git pull $USERNAME/$i"
       if [ -f "$REPODIR/gitmasterconfig" ]; then cp -Rf "$REPODIR/gitmasterconfig" "$REPODIR/.git/config"; fi
-      __devnull git -C "$PROJECT_DIR/$USERNAME/$i" pull --recurse-submodules -f -q
+      __devnull __git_pull "$PROJECT_DIR/$USERNAME/$i" --recurse-submodules
       __getexitcode "$SUCCES" "$ERROR"
     else
       ERROR="Git clone $USERNAME/$i failed"
       SUCCES="Git clone $USERNAME/$i completed"
       printf_purple "Now running git clone $USERNAME/$i"
-      __devnull git -C "$PROJECT_DIR/$USERNAME/$i" clone --recurse-submodules -f -q "$REPO_URL/$i"
+      __devnull __git_clone "$PROJECT_DIR/$USERNAME/$i" "$REPO_URL/$i" --recurse-submodules -f -q
       __getexitcode "$SUCCES" "$ERROR"
     fi
   done
@@ -409,27 +427,30 @@ main() {
 # push local repo
 git_push_single() {
   [ "$1" = "--help" ] || [ $# -eq 0 ] && printf_help "Usage: gitadmin push MyProjectDir"
+  local REPODIR="${1:-$REPODIR}"
+  SUCCESS_MSG() { echo "Push to $(__git_remote_origin "$REPODIR") has completed"; }
+  FAILED_MSG() { echo "Push to $(__git_remote_origin "$REPODIR") has failed"; }
   if [ -d "$REPODIR/.git" ]; then
-    printf_custom "4" "Pushing the repo in $PWD to $(__git_remote_origin "$REPODIR")"
-    __devnull2 git -C "$REPODIR" push -q
-    __getexitcode "Push has completed"
+    printf_custom "4" "Pushing the repo in $REPODIR"
+    __devnull2 __git_push "$REPODIR" && exitCode=0 || exitCode=1
+    __getexitcode $exitCode "$(SUCCESS_MSG)" "$(FAILED_MSG)"
   else
     if [ -n "$1" ]; then
       projdir="$1"
-      REPODIRname="$(__git_hostname "$1")"
+      REPODIR_NAME="$(__git_hostname "$1")"
       __git_username_repo "$1"
     else
-      projdir="$PROJECT_BASE/$REPODIRname/$username/$userrepo"
+      projdir="$PROJECT_BASE/$REPODIR_NAME/$username/$userrepo"
     fi
     if [ -d "$projdir/.git" ]; then
       printf_custom "4" "Pushing the repo in $projdir to $(__git_remote_origin "$projdir")"
-      __devnull git -C "$projdir" push -q
-      __getexitcode "Push has completed"
+      __devnull __git_push "$projdir" && exitCode=0 || exitCode=1
+      __getexitcode $exitCode "$(SUCCESS_MSG)" "$(FAILED_MSG)"
     else
       return 1
     fi
   fi
-  exit "$?"
+  return "$?"
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -437,21 +458,23 @@ git_push_single() {
 git_pull_single() {
   [ "$1" = "--help" ] || [ $# -eq 0 ] && printf_help "Usage: gitadmin pull MyProjectDir"
   if [ -d "$REPODIR/.git" ]; then
-    printf_custom "4" "Pulling the repo in $PWD from $(__git_remote_pull "$REPODIR")"
-    __devnull2 git -C "$REPODIR" pull -q
-    __getexitcode "Pulling has completed"
+    SUCCESS_MSG() { echo "Pull from $(__git_remote_origin "$REPODIR") has completed"; }
+    FAILED_MSG() { echo "Pull from $(__git_remote_origin "$REPODIR") has failed"; }
+    printf_custom "4" "Pulling the repo in $REPODIR"
+    __devnull2 git -C "$REPODIR" pull -q && exitCode=0 || exitCode=1
+    __getexitcode $exitCode "$(SUCCESS_MSG)" "$(FAILED_MSG)"
   else
     if [ -n "$1" ]; then
       projdir="$1"
-      REPODIRname="$(__git_hostname "$1")"
+      REPODIR_NAME="$(__git_hostname "$1")"
       __git_username_repo "$1"
     else
-      projdir="$PROJECT_BASE/$REPODIRname/$username/$userrepo"
+      projdir="$PROJECT_BASE/$REPODIR_NAME/$username/$userrepo"
     fi
     if [ -d "$projdir/.git" ]; then
-      printf_custom "4" "Pulling the repo in $projdir from $(__git_remote_pull "$projdir")"
-      __devnull git -C "$projdir" pull -q
-      __getexitcode "Pulling has completed"
+      printf_custom "4" "Pulling the repo in $projdir"
+      __devnull __git_pull "$projdir" && exitCode=0 || exitCode=1
+      __getexitcode $exitCode "$(SUCCESS_MSG)" "$(FAILED_MSG)"
     else
       return 1
     fi
@@ -463,24 +486,21 @@ git_pull_single() {
 # clone a single repo
 git_clone_single() {
   [ "$1" = "--help" ] || [ $# -eq 0 ] && printf_help "Usage: gitadmin clone MyURL"
-  if [ -d "$1" ]; then
-    REPODIRname="local"
-    userrepo="$(__basename $1)"
-    username="$(basename "$(__basedir "$1")")"
-  else
-    REPODIRname="$(__git_hostname "$1")"
-    __git_username_repo "$1"
-  fi
-  projdir="${2:-$PROJECT_BASE/$REPODIRname/$username/$userrepo}"
-  __mkd "$projdir"
+  SUCCESS_MSG() { echo "Cloning from $(__git_remote_origin "$projdir") has completed"; }
+  FAILED_MSG() { echo "Cloning from $(__git_remote_origin "$projdir") has failed"; }
+  local PROJECT_DIR projectdir
+  local giturl="$1"
+  __git_username_repo "$giturl"
+  projdir="${2:-$projectdir}"
+  #printf_debug "giturl:$giturl" "userrepo:$userrepo" "username:$username" "projdir:$projdir"
   if [ -d "$projdir/.git" ]; then
-    printf_custom "4" "Updating the repo in $projdir from $(__git_remote_origin "$projdir")"
-    __devnull git -C "$projdir" pull -q
-    __getexitcode "Updating has completed"
+    printf_custom "4" "Updating the repo in $projdir"
+    __devnull __git_pull "$projdir" && exitCode=0 || exitCode=1
+    __getexitcode $exitCode "$(SUCCESS_MSG)" "$(FAILED_MSG)"
   else
-    printf_custom "4" "Cloning the repo to $projdir from $1"
-    __devnull git clone -q "$1" "$projdir"
-    __getexitcode "Cloning has completed"
+    printf_custom "4" "Cloning the repo to $projdir"
+    __devnull __git_clone "$giturl" "$projdir" && exitCode=0 || exitCode=1
+    __getexitcode $exitCode "$(SUCCESS_MSG)" "$(FAILED_MSG)"
   fi
   exit "$?"
 }
@@ -490,13 +510,13 @@ git_update_loop() {
   if [[ "$*" =~ "--while" ]]; then
     while true; do
       for project in $(ls -d ~/Projects/*/*/*); do
-        printf_green "Updating $project $(__devnull git -C $project pull -q) $(__getexitcode)"
+        printf_green "Updating $project $(__devnull __git_pull $project) $(__getexitcode)"
       done && clear
       printf_custom "3" "Sleeping for a minute $(sleep 60)"
     done
   else
     for project in $(ls -d ~/Projects/*/*/*); do
-      printf_green "Updating $project $(__devnull git -C $project pull -q) $(__getexitcode)"
+      printf_green "Updating $project $(__devnull __git_pull $project) $(__getexitcode)"
     done
   fi
 }
@@ -582,7 +602,13 @@ update)
 push)
   shift 1
   [ "$1" == "--help" ] && printf_help "Usage: $APPNAME push | push the repo"
-  git_push_single "$@"
+  if [ "$1" = "--all" ]; then
+    for dir in $(find "$HOME/Projects"/*/*/* -maxdepth 0 -type d); do
+      git_push_single "$dir"
+    done
+  else
+    git_push_single "$@"
+  fi
   ;;
 
 pull)
@@ -671,7 +697,7 @@ clone)
         [ -f "$PROJECT_DIR/$USERNAME/$i/version.txt" ] && date +"%m%d%Y%H%M-git" >"$PROJECT_DIR/$USERNAME/$i/version.txt"
         __devnull git -C "$PROJECT_DIR/$USERNAME/$i" add . &&
           __devnull git -C "$PROJECT_DIR/$USERNAME/$i" commit -a -m " ❇🦈🏠❗ General Fixes ❗🏠🦈❇ " &&
-          __devnull git -C "$PROJECT_DIR/$USERNAME/$i" push -q
+          __devnull __git_push "$PROJECT_DIR/$USERNAME/$i"
         __getexitcode
       fi
     fi
@@ -748,7 +774,7 @@ github) # github repo
     if [[ "$1" = "--help" ]]; then printf_exit "Create a new github project\n\t\tUsage: gitadmin github init RepoName"; fi
     do_not_add_a_url "$1"
     homerepo="$(echo "$HOME/Projects/github/$1" | __sed 's/\",// ; s/\.[^.]*$// ; s#"##g')"
-    mkdir -p "$HOME/Projects/github/$1"
+    __mkd "$HOME/Projects/github/$1"
     __cd_into "$homerepo"
     repos_init $REPODIR
     exit "$?"
@@ -762,10 +788,10 @@ github) # github repo
     homerepo="$(echo "$HOME/Projects/github/$1" | __sed 's/\",// ; s/\.[^.]*$// ; s#"##g')"
     if [ -d "$homerepo" ]; then
       printf_green "The repo already exists so attempting update"
-      git -C "$homerepo" pull -q
+      __git_pull "$homerepo"
     else
       printf_green "Cloning the repo from github.com/$1"
-      git clone -q "https://github.com/$1.git" "$homerepo"
+      __git_clone "https://github.com/$1.git" "$homerepo"
     fi
     __cd_into "$homerepo"
     exit "$?"
@@ -790,9 +816,9 @@ gitlab)
     if [[ "$1" = "--help" ]]; then printf_exit "Create a new gitlab project\n\t\tUsage: gitadmin gitlab init RepoName"; fi
     do_not_add_a_url "$1"
     homerepo="$(echo "$HOME/Projects/gitlab/$1" | __sed 's/\",// ; s/\.[^.]*$// ; s#"##g')"
-    mkdir -p "$HOME/Projects/gitlab/$1"
+    __mkd "$HOME/Projects/gitlab/$1"
     __cd_into "$homerepo"
-    repos_init $REPODIR
+    repos_init "$REPODIR"
     exit "$?"
     ;;
 
@@ -804,10 +830,10 @@ gitlab)
     homerepo="$(echo "$HOME/Projects/gitlab/$1" | __sed 's/\",// ; s/\.[^.]*$// ; s#"##g')"
     if [ -d "$homerepo" ]; then
       printf_green "The repo already exists so attempting update"
-      git -C "$homerepo" pull -q
+      __git_pull "$homerepo"
     else
       printf_green "Cloning the repo from gitlab.com/$1"
-      git clone -q "https://gitlab.com/$1.git" "$homerepo"
+      __git_clone "https://gitlab.com/$1.git" "$homerepo"
     fi
     __cd_into "$homerepo"
     exit "$?"
@@ -834,7 +860,7 @@ private)
     if [[ "$1" = "--help" ]]; then printf_exit "Create a new private project\n\t\tUsage: gitadmin private init RepoName"; fi
     do_not_add_a_url "$1"
     homerepo="$(echo "$HOME/Projects/private/$1" | __sed 's/\",// ; s/\.[^.]*$// ; s#"##g')"
-    mkdir -p "$HOME/Projects/private/$1"
+    __mkd "$HOME/Projects/private/$1"
     __cd_into "$homerepo"
     repos_init $REPODIR
     exit "$?"
@@ -848,10 +874,10 @@ private)
     homerepo="$(echo "$HOME/Projects/private/$1" | __sed 's/\",// ; s/\.[^.]*$// ; s#"##g')"
     if [ -d "$homerepo" ]; then
       printf_green "The repo already exists so attempting update"
-      git -C "$homerepo" pull -q
+      __git_pull "$homerepo"
     else
       printf_green "Cloning the repo from $PERSONAL_GIT_HOST/$1"
-      git clone -q "$PERSONAL_GIT_HOST/$1.git" "$homerepo"
+      __git_clone "$PERSONAL_GIT_HOST/$1.git" "$homerepo"
     fi
     __cd_into "$homerepo"
     exit "$?"
