🏠🐜❗ Minor Fixes ❗🐜🏠

diff --git a/bin/logr b/bin/logr
--- a/bin/logr
+++ b/bin/logr
@@ -32,10 +32,13 @@ fi
 printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
 printf_green() { printf_color "$1" 2; }
 printf_red() { printf_color "$1" 1; }
-
+printf_exit() {
+  printf_color "$1" 1
+  exit $?
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-set -o pipefail # trace ERR through pipes
+# trace ERR through pipes
+set -o pipefail
 shopt -s extglob
 
 logrname="${1:-$APPNAME}"
@@ -48,6 +51,11 @@ host="$(hostname -f)"
 if [ "$1" = "-name" ]; then
   logrname=$2
   shift 2
+fi
+if [ "$1" = "cron" ]; then
+  stdout="$2.log"
+  stderr="$2.err"
+  shift 1
 fi
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -81,36 +89,36 @@ case "$1" in
   cmdline="$*"
   echo -e "logr started $logrname on $(date +"%b %d, %Y at %H:%M")"
   echo -e "Full command is: $cmdline"
-  "$cmdline" 2>>$logdir/$logrname-$date.err
+  "$cmdline" 2>>$logdir/$stderr
   echo -e "App has ended on $(date +"%b %d, %Y at %H:%M")"
   ;;
 --err | -e)
   shift 1
   cmdline="$*"
-  echo -e "logr started $logrname $(date +"%b %d, %Y at %H:%M")" >>$logdir/$logrname-$date.log
-  echo -e "Full command is: $cmdline" >>$logdir/$logrname-$date.log
-  "$cmdline" >>$logdir/$logrname-$date.log
-  echo -e "App has ended on $(date +"%b %d, %Y at %H:%M")" >>$logdir/$logrname-$date.log
+  echo -e "logr started $logrname $(date +"%b %d, %Y at %H:%M")" >>$logdir/$stdout
+  echo -e "Full command is: $cmdline" >>$logdir/$stdout
+  "$cmdline" >>$logdir/$stdout
+  echo -e "App has ended on $(date +"%b %d, %Y at %H:%M")" >>$logdir/$stdout
   ;;
 --silent | -si)
   shift 1
   cmdline="$*"
-  echo -e "logr started $logrname $(date +"%b %d, %Y at %H:%M")" >>$logdir/$logrname-$date.log
-  echo -e "Full command is: $cmdline" >>$logdir/$logrname-$date.log
-  "$cmdline" >>$logdir/$logrname-$date.log 2>>$logdir/$logrname-$date.err
-  echo -e "App has ended on $(date +"%b %d, %Y at %H:%M")" >>$logdir/$logrname-$date.log
+  echo -e "logr started $logrname $(date +"%b %d, %Y at %H:%M")" >>$logdir/$stdout
+  echo -e "Full command is: $cmdline" >>$logdir/$stdout
+  "$cmdline" >>$logdir/$stdout 2>>$logdir/$stderr
+  echo -e "App has ended on $(date +"%b %d, %Y at %H:%M")" >>$logdir/$stdout
   ;;
 *)
   cmdline="$*"
-  echo -e "logr started $logrname $(date +"%b %d, %Y at %H:%M")" >>$logdir/$logrname-$date.log
-  echo -e "Full command is: $cmdline" >>$logdir/$logrname-$date.log
-  "$cmdline" >>$logdir/$logrname-$date.log 2>>$logdir/$logrname-$date.err
-  echo -e "App has ended on $(date +"%b %d, %Y at %H:%M")" >>$logdir/$logrname-$date.log
+  echo -e "logr started $logrname $(date +"%b %d, %Y at %H:%M")" >>$logdir/$stdout
+  echo -e "Full command is: $cmdline" >>$logdir/$stdout
+  "$cmdline" >>$logdir/$stdout 2>>$logdir/$stderr
+  echo -e "App has ended on $(date +"%b %d, %Y at %H:%M")" >>$logdir/$stdout
   ;;
 esac
 
-if [ -d "$logdir" ] && [ -n "$(ls -A $logdir/$logrname-$date.* 2>/dev/null)" ]; then
-  for upd in $(ls $logdir/$logrname-$date.* 2>/dev/null); do
+if [ -d "$logdir" ] && [ -n "$(ls -A $logdir/$logrname* 2>/dev/null)" ]; then
+  for upd in $(ls $logdir/$logrname* 2>/dev/null); do
     file="$(ls -A $logdir/$upd 2>/dev/null)"
     if [ -f "$file" ]; then
       sed -i "s,\x1B\[[0-9;]*[a-zA-Z],,g" "$file"
@@ -119,23 +127,29 @@ if [ -d "$logdir" ] && [ -n "$(ls -A $logdir/$logrname-$date.* 2>/dev/null)" ]; 
   done
 fi
 
-if cmd_exists mail && [ -s $logdir/$logrname-$date.err ] && [ -n "$EMAIL_ERROR" ]; then
+if cmd_exists mail && [ -s $logdir/$stderr ] && [ -n "$EMAIL_ERROR" ]; then
   MAILFROM="${MAILFROM:-root@$host}"
   MAILRECIP="${MAILRECIP:-$USER@$host}"
   MAILSUB="logr: $logrname"
   MAILHEADER="The $logrname script has been ran on $(hostname -s)"
-  cat $logdir/$logrname-$date.err | devnull mail -r "$MAILFROM" -s "$MAILSUB" $MAILRECIP
+  cat $logdir/$stderr | devnull mail -r "$MAILFROM" -s "$MAILSUB" $MAILRECIP
   echo -e "
 Email Sent On: $(date +"%b %d, %Y at %H:%M")\n
 Mail From: $MAILFROM
 Mail Subject: $MAILSUB
 Mail To: $MAILRECIP
-Log File: $logdir/$logrname-$date.err
+Log File: $logdir/$stderr
 " >$logdir/$logrname-$date.sent
 fi
 
-if [ -n "$DESKTOP_SESSION" ] && [ -s $logdir/$logrname-$date.err ]; then
+if [ -n "$DESKTOP_SESSION" ] && [ -s $logdir/$stderr ]; then
   notifications "$logrname completed" "The task has finished with errors: check the log"
+fi
+
+#clean up
+if [ -s $logdir/$stderr ]; then
+  cat $logdir/$stderr >>$logdir/$stdout
+  rm -Rf $logdir/$stderr
 fi
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
