🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/notes b/bin/notes
--- a/bin/notes
+++ b/bin/notes
@@ -11,7 +11,7 @@ USER="${SUDO_USER:-${USER}}"
 # @Created     : Wed, Aug 05, 2020, 02:00 EST
 # @License     : WTFPL
 # @Copyright   : Copyright (c) CasjaysDev
-# @Description : take notes using bash
+# @Description : Take notes using bash
 #
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
@@ -33,23 +33,21 @@ fi
 user_install
 __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-NOTES_NOTIFY="yes"
-NOTES_TMPDIR="${TMP:-/tmp}"
 NOTES_FOLDER="$(date +%Y)"
 NOTES_FILE="$(date +%m).txt"
 NOTES_PREV_MONTH="$(date --date="1 Month Ago" +%m).txt"
+NOTES_NOTIFY="yes"
+NOTES_TMPDIR="${TMP:-/tmp}/notes"
 NOTES_DIRECTORY="${NOTES_DIRECTORY:-"$HOME/.local/share/editors/notes"}"
 NOTES_EDITOR="${NOTES_EDITOR:-vim}"
-NOTES_SERVER_NAME="${NOTES_SERVER_NAME:-localhost}"
+NOTES_SERVER_NAME="${NOTES_SERVER_NAME:-}"
 NOTES_SERVER_PORT="${NOTES_SERVER_PORT:-65000}"
 NOTES_SERVER_DIRECTORY="$NOTES_DIRECTORY"
 NOTES_LOG_FILE="${NOTES_TMPDIR}/notes_server.log"
-NOTES_TMP_FILE="$(mktemp $NOTES_TMPDIR/notes.XXXXXX.txt 2>/dev/null)"
+NOTES_TMP_FILE="$(mktemp $NOTES_TMPDIR/notes.XXXXXX.tmp 2>/dev/null)"
 NOTES_PATH="$NOTES_DIRECTORY/$NOTES_FOLDER/$NOTES_FILE"
 NOTES_SERVER_PATH="$NOTES_SERVER_DIRECTORY/$NOTES_FOLDER/$NOTES_FILE"
 NOTES_PREV_FILE="$NOTES_SERVER_DIRECTORY/$NOTES_FOLDER/$NOTES_PREV_MONTH"
-
-netcat="$(command -v nc 2>/dev/null || command -v netcat 2>/dev/null)"
 
 [ -f "$HOME/.config/notes/config" ] && . "$HOME/.config/notes/config"
 
@@ -96,7 +94,7 @@ NOTES_SERVER_NAME="'${NOTES_SERVER_NAME:-localhost}'"
 NOTES_SERVER_PORT="'${NOTES_SERVER_PORT:-65000}'"
 NOTES_SERVER_DIRECTORY="'${NOTES_DIRECTORY}'"
 NOTES_LOG_FILE="'${NOTES_TMPDIR}/notes_server.log'"
-NOTES_TMP_FILE="$(mktemp ${NOTES_TMPDIR}/notes.XXXXXX.txt 2>/dev/null)"
+NOTES_TMP_FILE="$(mktemp ${NOTES_TMPDIR}/notes.XXXXXX.tmp 2>/dev/null)"
 NOTES_PATH="${NOTES_DIRECTORY}/${NOTES_FOLDER}/${NOTES_FILE}"
 NOTES_SERVER_PATH="${NOTES_SERVER_DIRECTORY}/${NOTES_FOLDER}/${NOTES_FILE}"
 NOTES_NOTIFY="${NOTES_NOTIFY:-yes}"
@@ -120,17 +118,19 @@ Group='${USER:-daemon}'
 
 Environment=HOME='${HOME}'
 Environment=TERM='${TERM:-linux}'
-Environment=NOTES_TMPDIR='${TMP:-/tmp/notes_server}'
+Environment=NOTES_TMPDIR='${TMP:-/tmp}/notes_server'
 Environment=NOTES_DIRECTORY='${HOME}/.local/share/editors/notes'
 Environment=NOTES_LOG_FILE='${NOTES_TMPDIR}/notes_server.log'
 Environment=NOTES_SERVER_NAME="$(hostname -f)"
 Environment=NOTES_SERVER_PORT=65000
-Environment=NOTES_TMP_FILE="$(mktemp $NOTES_TMPDIR/notes.XXXXXX.txt 2>/dev/null)"
+Environment=NOTES_TMP_FILE="$(mktemp $NOTES_TMPDIR/notes.XXXXXX.tmp 2>/dev/null)"
+Environment=NOTES_NOTIFY='${NOTES_NOTIFY:-yes}'
 
-ExecStartPre=/usr/local/bin/notes server systemd vars
-ExecStartPre=/bin/mkdir -p "$NOTES_DIRECTORY"
-ExecStart=/bin/bash -c "/usr/local/bin/notes server systemd run"
-ExecStopPost=/usr/bin/rm -Rf "$NOTES_TMP_FILE $NOTES_LOG_FILE"
+ExecStartPre=/bin/mkdir -p "$NOTES_DIRECTORY" "$NOTES_TMPDIR"
+ExecStartPre=/usr/local/bin/notes server systemd run vars
+ExecStopPost=/usr/bin/rm -Rf "$NOTES_TMPDIR $NOTES_LOG_FILE"
+ExecStopPost=/bin/bash -c "/usr/local/bin/notes server systemd stop"
+ExecStart=/bin/bash -c "/usr/local/bin/notes server systemd run start"
 ExecStop=/bin/kill -s KILL $MAINPID
 TimeoutSec=20
 RemainAfterExit=yes
@@ -140,16 +140,45 @@ WantedBy=multi-user.target
 ' | sudo tee "$1" &>/dev/null
 }
 
+__server_enable() {
+  printf_green "Enabling the Notes Server on port $NOTES_SERVER_PORT"
+  cat <<EOF >"$HOME/.config/autostart/notes-server.desktop"
+#!/usr/bin/env xdg-open
+
+[Desktop Entry]
+Version=1.1
+Type=Application
+Name=Notes Server
+GenericName=NotesServer
+Comment=Start Notes Server.
+Icon=geany
+Exec=notes server start &
+Path=~
+Terminal=false
+Actions=
+Categories=System;Development;GTK;X-XFCE;GNOME;
+Keywords=notes;server;
+StartupNotify=true
+EOF
+  notes server start &
+  exit
+}
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 _debug() {
   echo $NOTES_FOLDER $NOTES_FILE $NOTES_TMPDIR $NOTES_DIRECTORY $NOTES_EDITOR $NOTES_SERVER_NAME $NOTES_SERVER_PORT $NOTES_SERVER_DIRECTORY $NOTES_LOG_FILE $NOTES_TMP_FILE $NOTES_PATH $NOTES_SERVER_PATH
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-__netcat_test() { __cmd_exists $netcat || printf_exit "The program netcat is not installed"; }
-__nc_send() { $netcat -c $1 $2 2>>"$NOTES_LOG_FILE" && true || $netcat -w 1 $1 $2 2>>"$NOTES_LOG_FILE" || return 1; }
+#__netcat_test() { __netcat_test || printf_exit "The program netcat is not installed"; }
+__nc_send() { __netcat -c $1 $2 2>>"$NOTES_LOG_FILE" && true || __netcat -w 1 $1 $2 2>>"$NOTES_LOG_FILE" || return 1; }
 __notes() { eval tmux -f "${NOTES_DIRECTORY}/tmux.conf" new-session -D -A -s notes "vim ${1:-$NOTES_PATH}" &>/dev/null; }
 __dedupe() { cat "$1" | grep -v "$2"; }
+__kill_server() {
+  __netcat_kill "${1:-$NOTES_SERVER_PORT}" >/dev/null 2>&1 &&
+    ${2:-echo} "${3:-Server has been stopped}" || ${2:-echo} "${3:-Failed to stop}"
+  sleep 2
+}
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __sync() {
@@ -165,23 +194,31 @@ __sync() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 __server() {
-  local _PORT=${NOTES_SERVER_PORT}
-  local _PATH="$NOTES_TMP_FILE"
+  echo ""
+  local _PORT="${NOTES_SERVER_PORT}"
+  local _PATH="${NOTES_TMP_FILE}"
+  local _KILL="$NOTES_TMPDIR/kill_notes"
+  local _NOTES_NOTIFY=${NOTES_NOTIFY:-yes}
+  __rm_rf "$_KILL" "$NOTES_LOG_FILE" "$NOTES_TMPDIR"
+  __mkd "$NOTES_TMPDIR"
   __netcat_test
   netstatg "$_PORT" &>/dev/null && printf_exit "Already Running" || printf_green "Launching server on port $_PORT"
+  notifications "Notes Server" "Launching server on port $_PORT"
   echo "Starting notes server on port $_PORT" >"$NOTES_LOG_FILE"
-  rm -Rf $NOTES_TMPDIR/kill_notes
   while :; do
-    $netcat -l -p $_PORT >"$_PATH"
-    cat $_PATH >>"${NOTES_PATH}" 2>>"$NOTES_LOG_FILE"
-    [ "$NOTES_NOTIFY" = "yes" ] && notifications "New note" "$(cat $_PATH)\nPosted to: ${NOTES_PATH}"
-    if [ -f $NOTES_TMPDIR/kill_notes ]; then
-      rm -Rf $NOTES_TMPDIR/kill_notes
+    rm -Rf "$_PATH"
+    __netcat -l -p $_PORT >"$_PATH"
+    cat "$_PATH" >>"${NOTES_PATH}" 2>>"$NOTES_LOG_FILE"
+    message="$(<"$_PATH")"
+    echo "New note: $message" >>"$NOTES_LOG_FILE"
+    [ -z "$message" ] || [ "$_NOTES_NOTIFY" = "yes" ] && notifications "New note" "$message\nPosted to: ${NOTES_PATH}"
+    if [ -f "$_KILL" ]; then
+      rm -Rf "$_KILL"
       echo "Notes server is shutting down" >>"$NOTES_LOG_FILE"
+      notifications "Notes Server" "Notes server is shutting down"
       break
     fi
   done
-  rm -Rf "$_PATH"
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -189,19 +226,26 @@ __server() {
 __run_service() {
   local _PORT="${NOTES_SERVER_PORT}"
   local _PATH="${NOTES_TMP_FILE}"
-  local NOTES_NOTIFY=${NOTES_NOTIFY:-yes}
-  local DISPLAY="${DISPLAY:-:0.0}"
-  kill -s KILL "$(netstatg $_PORT | awk '{print $7}' | head -n 1 | sed 's#/.*##g')" || true
+  local _KILL="$NOTES_TMPDIR/kill_notes"
+  local _NOTES_NOTIFY=${NOTES_NOTIFY:-yes}
   echo "Launching server on port $_PORT"
   echo "Starting notes server on port $_PORT" >"$NOTES_LOG_FILE"
-  rm -Rf "$NOTES_TMPDIR/kill_notes"
+  __rm_rf "$_KILL" "$NOTES_LOG_FILE" "$NOTES_TMPDIR"
+  __mkd "$NOTES_TMPDIR"
+  __netcat_test
   while :; do
     rm -Rf "$_PATH"
-    $netcat -l -p "$_PORT" >"$_PATH"
+    __netcat -l -p "$_PORT" >"$_PATH"
     cat "$_PATH" >>"${NOTES_PATH}" 2>>"$NOTES_LOG_FILE"
     echo "New note: $(cat $_PATH) in ${NOTES_PATH}"
-    [ "$NOTES_NOTIFY" = "yes" ] && notifications "New note" "$(cat $_PATH)\nPosted to: ${NOTES_PATH}" && echo "notification sent"
+    [ "$_NOTES_NOTIFY" = "yes" ] && notifications "New note" "$(cat $_PATH)\nPosted to: ${NOTES_PATH}" && echo "notification sent"
     rm -Rf "$_PATH"
+    if [ -f "$_KILL" ]; then
+      __kill_server "$_PORT" &>/dev/null
+      __rm_rf "$_LOG"
+      echo "Daemon" "notes server is shutting down"
+      break
+    fi
   done
 }
 
@@ -231,7 +275,8 @@ __import() {
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-mkdir -p "${NOTES_DIRECTORY}/$NOTES_FOLDER"
+__mkd "$NOTES_TMPDIR" "${NOTES_DIRECTORY}/$NOTES_FOLDER"
+__rm_rf ${TMP:-/tmp}/notes/notes*.tmp
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Previous month
 if [ ! -f "$NOTES_PATH" ]; then
@@ -244,6 +289,7 @@ if [ ! -f "$NOTES_PATH" ]; then
     __import && sleep 3
   fi
 fi
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 case $1 in
 --import)
@@ -259,14 +305,16 @@ server | service)
   if [ "$2" = "--help" ]; then shift 1 && printf_help 'Usage: notes server  |  Start the server'; fi
   if [ "$2" = "--status" ]; then
     shift 1
-    netstatg "$NOTES_SERVER_PORT" 2>/dev/null
+    netstatg "$NOTES_SERVER_PORT" 2>/dev/null | printf_readline
     exit 0
   fi
   if [ "$2" = "--kill" ]; then
-    printf_exit "Starting shutdown"
+    printf_red "Starting shutdown"
     shift 1
-    touch $NOTES_TMPDIR/kill_notes >/dev/null 2>&1
-    kill -s 9 "$(netstatg $NOTES_SERVER_PORT | awk '{print $7}' | head -n 1 | sed 's#/.*##g')" || true
+    touch "$NOTES_TMPDIR/kill_notes"
+    __kill_server "$NOTES_SERVER_PORT" "printf_green"
+    #kill -s 9 "$(netstatg $NOTES_SERVER_PORT | awk '{print $7}' | head -n 1 | sed 's#/.*##g')" || true
+    exit $?
   fi
 
   # begin systemd
@@ -274,6 +322,30 @@ server | service)
   systemd)
     shift 1
     case $2 in
+    run)
+      case $3 in
+      vars)
+        shift 2
+        export NOTES_NOTIFY NOTES_FOLDER NOTES_FILE NOTES_TMPDIR NOTES_DIRECTORY NOTES_EDITOR NOTES_PATH
+        export NOTES_SERVER_NAME NOTES_SERVER_PORT NOTES_SERVER_DIRECTORY NOTES_LOG_FILE NOTES_TMP_FILE NOTES_SERVER_PATH
+        ;;
+      stop)
+        shift 2
+        touch "$NOTES_TMPDIR/kill_notes"
+        __kill_server "$NOTES_SERVER_PORT"
+        ;;
+      start)
+        shift 2
+        opts="$*"
+        __run_service "$opts" 2>>"$NOTES_LOG_FILE"
+        ;;
+      *)
+        shift 2
+        opts="$*"
+        __run_service "$opts" 2>>"$NOTES_LOG_FILE"
+        ;;
+      esac
+      ;;
     install)
       shift 2
       NOTES_DIRECTORY="$NOTES_SERVER_DIRECTORY"
@@ -300,15 +372,6 @@ server | service)
       shift 2
       __devnull sudo systemctl restart notes_server && printf_green "Service has been restarted" || printf_red "Failed to restart service"
       ;;
-    run)
-      shift 2
-      opts="$*"
-      __run_service "$opts" 2>>"$NOTES_LOG_FILE"
-      ;;
-    vars)
-      shift 2
-      export NOTES_FOLDER NOTES_FILE NOTES_TMPDIR NOTES_DIRECTORY NOTES_EDITOR NOTES_SERVER_NAME NOTES_SERVER_PORT NOTES_SERVER_DIRECTORY NOTES_LOG_FILE NOTES_TMP_FILE NOTES_PATH NOTES_SERVER_PATH
-      ;;
     status | *)
       shift 2
       sudo systemctl status notes_server | printf_readline "255"
@@ -322,10 +385,16 @@ server | service)
     [ "$2" = "all" ] && ssh -qt "$NOTES_SERVER_NAME" notes all || ssh -qt "$NOTES_SERVER_NAME" notes
     ;;
 
+  start)
+    shift 1
+    opts="$*"
+    __server "$opts" 2>>"$NOTES_LOG_FILE"
+    ;;
+
   *)
     shift 1
     opts="$*"
-    __server "$opts" 2>>"$NOTES_LOG_FILE" &
+    __server "$opts" 2>>"$NOTES_LOG_FILE"
     ;;
   esac
   ;;
diff --git a/templates/scripts/shell/case b/templates/scripts/shell/case
--- a/templates/scripts/shell/case
+++ b/templates/scripts/shell/case
@@ -37,7 +37,8 @@ user_install
 __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Check for needed applications
-check_app
+__check_app bash            #graphical prompt
+__cmd_exists bash || exit 1 # return 1 if not found
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set variables
@@ -46,26 +47,41 @@ check_app
 # Set functions
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Set up the case statements
+# Set additional variables
 
-while getopts ":hv" opt; do
-  case $opt in
-  v | version)
-    echo "$0 -- Version"
-    get_app_info
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# bring in user config
+[ -f "$HOME/.config/$APPNAME/settings" ] && . "$HOME/.config/$APPNAME/settings"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Set up the case statements
+t=$(getopt -o h,t:,n: --long help,title:,name: -n "$APPNAME" -- "$@") #get options
+eval set -- "$t"                                                      #set
+
+while :; do
+  case "$1" in
+  -h | --help)
+    usage
     exit 0
     ;;
-  h | help)
-    __help
-    exit 0
+  -t | --title)
+    shift
+    title="$1"
+    ;;
+  -n | --name)
+    shift
+    name="$1"
+    ;;
+  --)
+    shift
+    break
     ;;
   *)
-    printf_error "Option does not exist : $OPTARG"
-    __help
+    echo >&2 "$APPNAME: Internal error: [$1] not recognized!"
+    exit 1
     ;;
   esac
+  shift
 done
-shift $(($OPTIND - 1))
 
 case "$1" in
 config)
