🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/notes b/bin/notes
--- a/bin/notes
+++ b/bin/notes
@@ -42,7 +42,7 @@ __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Default variables
 NOTES_NOTIFY="yes"
-NOTES_TMPDIR="${TMP:-/tmp}"
+NOTES_TMPDIR="${TMP:-/tmp}/notes"
 NOTES_FOLDER="$(date +%Y)"
 NOTES_FILE="$(date +%m).txt"
 NOTES_PREV_MONTH="$(date --date="1 Month Ago" +%m).txt"
@@ -51,17 +51,20 @@ NOTES_EDITOR="${NOTES_EDITOR:-vim}"
 NOTES_SERVER_NAME="${NOTES_SERVER_NAME:-localhost}"
 NOTES_SERVER_PORT="${NOTES_SERVER_PORT:-65000}"
 NOTES_SERVER_DIRECTORY="$NOTES_DIRECTORY"
+NOTES_SERVER_TIMEOUT="${NOTES_SERVER_TIMEOUT:-600}"
 NOTES_LOG_FILE="${NOTES_TMPDIR}/notes_server.log"
 NOTES_TMP_FILE="$(mktemp $NOTES_TMPDIR/notes.XXXXXX.txt 2>/dev/null)"
 NOTES_PATH="$NOTES_DIRECTORY/$NOTES_FOLDER/$NOTES_FILE"
 NOTES_SERVER_PATH="$NOTES_SERVER_DIRECTORY/$NOTES_FOLDER/$NOTES_FILE"
 NOTES_PREV_FILE="$NOTES_SERVER_DIRECTORY/$NOTES_FOLDER/$NOTES_PREV_MONTH"
 NOTES_NOTIFY="${NOTES_NOTIFY:-yes}"
+NOTES_DEDUP_NOTIFY=""
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Import settings
 [ -f "$HOME/.config/notes/config" ] && . "$HOME/.config/notes/config"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __mkd "$NOTES_DIRECTORY"
+__mkd "$NOTES_TMPDIR"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Tmux config
 if [ ! -f "$NOTES_DIRECTORY/tmux.conf" ]; then
@@ -72,24 +75,26 @@ if [ ! -f "$NOTES_DIRECTORY/tmux.conf" ]; then
   fi
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-_notifications() { [ "$NOTES_NOTIFY" = "yes" ] && notifications "$@"; }
+_notifications() { if [ "$NOTES_NOTIFY" = "yes" ]; then notifications "$@"; fi; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Generate config file
 gen_config() {
   __mkd "$HOME/.config/notes"
   echo 'NOTES_FOLDER="$(date +%Y)"
 NOTES_FILE="$(date +%m).txt"
-NOTES_TMPDIR="'${TMP:-/tmp}'"
+NOTES_TMPDIR="'${TMP:-/tmp}'/notes"
 NOTES_DIRECTORY="'${NOTES_DIRECTORY:-"$HOME/.local/share/editors/notes"}'"
 NOTES_EDITOR="'${NOTES_EDITOR:-vim}'"
 NOTES_SERVER_NAME="'${NOTES_SERVER_NAME:-localhost}'"
 NOTES_SERVER_PORT="'${NOTES_SERVER_PORT:-65000}'"
 NOTES_SERVER_DIRECTORY="'${NOTES_DIRECTORY}'"
+NOTES_SERVER_TIMEOUT="'${NOTES_SERVER_TIMEOUT:-600}'"
 NOTES_LOG_FILE="'${NOTES_TMPDIR}/notes_server.log'"
 NOTES_TMP_FILE="$(mktemp ${NOTES_TMPDIR}/notes.XXXXXX.txt 2>/dev/null)"
 NOTES_PATH="${NOTES_DIRECTORY}/${NOTES_FOLDER}/${NOTES_FILE}"
 NOTES_SERVER_PATH="${NOTES_SERVER_DIRECTORY}/${NOTES_FOLDER}/${NOTES_FILE}"
 NOTES_NOTIFY="${NOTES_NOTIFY:-yes}"
+NOTES_DEDUP_NOTIFY=""
 ' >"$HOME/.config/notes/config"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -169,15 +174,19 @@ EOF
 netcat="$(command -v nc 2>/dev/null || command -v netcat 2>/dev/null)"
 __netcat_test() { __cmd_exists $netcat || printf_exit "The program netcat is not installed"; }
 __nc_send() { $netcat -c $1 $2 2>>"$NOTES_LOG_FILE" && true || $netcat -w 1 $1 $2 2>>"$NOTES_LOG_FILE" || return 1; }
-__local() { if [ "$NOTES_SERVER_NAME" = "$(hostname -f)" ] || [ "$NOTES_SERVER_NAME" = "$(hostname -s)" ] || \
+__local() { if [ "$NOTES_SERVER_NAME" = "$(hostname -f)" ] || [ "$NOTES_SERVER_NAME" = "$(hostname -s)" ] ||
   [ "$NOTES_SERVER_NAME" = "localhost" ]; then return 1; else return 0; fi; }
-  __notes() { eval tmux -f "${NOTES_DIRECTORY}/tmux.conf" new-session -D -A -s notes "${NOTES_EDITOR:-vim} ${1:-$NOTES_PATH}" &>/dev/null || return 1; }
+__notes() { eval tmux -f "${NOTES_DIRECTORY}/tmux.conf" new-session -D -A -s notes "${NOTES_EDITOR:-vim} ${1:-$NOTES_PATH}" &>/dev/null || return 1; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __dedup() {
+  local _MSG="$1"
   local _NOTESP=${2:-$NOTES_PATH}
-  if grep -qx "$1" "$_NOTESP"; then
-    DEDUP=false
-    _notifications "NotesCLI" "Note has already been added to $_NOTESP"
+  shift $#
+  if grep -qx "$_MSG" "$_NOTESP"; then
+    DEDUP=true
+    if [ "${NOTES_DEDUP_NOTIFY:-$DEDUP_NOTIFY}" = "yes" ] && ${3:-true}; then
+      _notifications "NotesCLI" "$_MSG already added to $_NOTESP"
+    fi
     return 1
   else
     return 0
@@ -186,16 +195,18 @@ __dedup() {
 #__update_notes "$message" "${NOTES_PATH}"
 __update_notes() {
   if __dedup "$1" "$2"; then
-    printf "%s\n" "$1" >>"${NOTES_PATH}" && _notifications "New Note" "$1\nposted to\n$2"
+    printf "%s\n" "$1" >>"${2:-$NOTES_PATH}" 2>>"${3:-$NOTES_LOG_FILE}" && exitCode=0 && _notifications "New Note" "$1\nposted to\n$2"
+    if [ "$exitCode" -ne 0 ]; then _notifications "Failed to commit the note"; fi
   else
-    return 1
+    exitCode=1
   fi
+  return "${exitCode:-$?}"
 }
 __sync_tmp() {
   local _NOTESP="${1:-$NOTES_PATH}"
   local _TPATH="${2:-$_PATH}"
   shift
-  if [ -n "$_TPATH" ]; then cat "$_NOTESP" "$_TPATH" >"$NOTES_TMPDIR/notes_cli.tmp" && \
+  if [ -n "$_TPATH" ]; then cat "$_NOTESP" "$_TPATH" >"$NOTES_TMPDIR/notes_cli.tmp" &&
     __mv_f "$NOTES_TMPDIR/notes_cli.tmp" "$_NOTESP"; fi
   [ -f "$NOTES_DIRECTORY/all.txt" ] && __sync_all && echo synced >>"$NOTES_LOG_FILE"
 }
@@ -231,69 +242,101 @@ __sync_all() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Server function for user autostart
 __server() {
-  echo ""
-  local _PORT="${NOTES_SERVER_PORT}"
+  [ "$1" = "--loop" ] && NOTES_SERVER_LOOP="yes"
+  local _PORT="$NOTES_SERVER_PORT"
   local _KILL="$NOTES_TMPDIR/kill_notes"
-  local _TMPFILE="$(mktemp $NOTES_TMPDIR/notes.server.XXXXXXX.tmp 2>/dev/null)"
-  __rm_rf "$_KILL" "$NOTES_LOG_FILE" "$NOTES_TMPDIR"
+  local _TMPFILE="$NOTES_TMP_FILE"
   __mkd "$NOTES_TMPDIR"
   __netcat_test
   netstatg "$_PORT" &>/dev/null && printf_exit "Already Running" || printf_green "Launching server on port $_PORT"
-  _notifications "Notes Server" "Launching server on port $_PORT"
-  echo "Starting notes server on port $_PORT" >"$NOTES_LOG_FILE"
-  while :; do
-    rm -Rf "$_TMPFILE"
-    $netcat -l -p $_PORT >"$_TMPFILE"
-    cat "$_TMPFILE" >>"${NOTES_PATH}" 2>>"$NOTES_LOG_FILE" || _notifications "Failed to commit the note"
-    message="$(<"$_TMPFILE")"
-    if [ -f "$_KILL" ]; then
-      rm -Rf "$_KILL"
-      echo "Notes server is shutting down" >>"$NOTES_LOG_FILE"
-      _notifications "Notes Server" "Notes server is shutting down"
-      break && exit $?
-    fi
-    [ -z "$message" ] || echo "New note: $message" >>"$NOTES_LOG_FILE"
-    [ -z "$message" ] || _notifications "New note" "$message\nPosted to: ${NOTES_PATH}"
-  done
+  if [ "$NOTES_SERVER_LOOP" != "yes" ]; then
+    _notifications "Notes Server" "Launching server on port $_PORT"
+    echo "Starting notes server on port $_PORT" >>"$NOTES_LOG_FILE"
+  fi
+  timeout ${NOTES_SERVER_TIMEOUT:-600} $netcat -l -p $_PORT >"$_TMPFILE"
+  message="$(<"$_TMPFILE")"
+  if __dedup "$message" "$NOTES_PATH" "__file_not_empty $_TMPFILE"; then
+    __update_notes "$message" "$NOTES_PATH" "$NOTES_LOG_FILE"
+  else
+    errormsg="$message seemes to be duplicate"
+  fi
+  if [ -n "$message" ] && [ -z "$DEDUP" ]; then
+    echo "New note: $message" >>"$NOTES_LOG_FILE"
+  else
+    echo "NotesCLI" "Problem receiving message: ${errormsg:-File is empty}" >>"$NOTES_LOG_FILE"
+  fi
+  __rm_rf "$_TMPFILE"
+  if [ -f "$_KILL" ]; then
+    rm -Rf "$_KILL"
+    echo "Notes server is shutting down" >>"$NOTES_LOG_FILE"
+    _notifications "Notes Server" "Notes server is shutting down"
+    exit $?
+  fi
+  __server --loop
+  #notes --server --start --loop
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Server function for SystemD
 __run_service() {
-  local _PORT="${NOTES_SERVER_PORT}"
-  local _PATH="${NOTES_TMP_FILE}"
+  local _PORT="$NOTES_SERVER_PORT"
+  local _PATH="$NOTES_TMP_FILE"
   local NOTES_NOTIFY=${NOTES_NOTIFY:-yes}
   local DISPLAY="${DISPLAY:-:0.0}"
   kill -s KILL "$(netstatg $_PORT | awk '{print $7}' | head -n 1 | sed 's#/.*##g')" || true
-  echo "Launching server on port $_PORT"
-  echo "Starting notes server on port $_PORT" >"$NOTES_LOG_FILE"
+  if [ "$NOTES_SERVER_LOOP" != "yes" ]; then
+    echo "Launching server on port $_PORT"
+    echo "Starting notes server on port $_PORT" >"$NOTES_LOG_FILE"
+  fi
   rm -Rf "$NOTES_TMPDIR/kill_notes"
-  while :; do
-    rm -Rf "$_PATH"
-    $netcat -l -p "$_PORT" >"$_PATH"
+  rm -Rf "$_PATH"
+  timeout ${NOTES_SERVER_TIMEOUT:-600} $netcat -l -p "$_PORT" >"$_PATH"
+  if __file_not_empty "$_PATH"; then
     cat "$_PATH" >>"${NOTES_PATH}" 2>>"$NOTES_LOG_FILE" || echo "Failed to commit the note"
     echo "New note: $(cat $_PATH) in ${NOTES_PATH}"
-    rm -Rf "$_PATH"
-  done
+  fi
+  rm -Rf "$_PATH"
+  notes --server --systemd --run --start
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Client function
 __client() {
   __failed() {
+    _notifications "${1:-NotesCLI}" "${2:-$MESSAGE Failed to send}"
     printf_red "failed to send message"
     return 1
   }
+  __success() {
+    _notifications "${1:-NotesCLI}" "${2:-$MESSAGE has been sent}"
+    return 0
+  }
+  local MESSAGE="$1"
+  local DEDUP_NOTIFY="${DEDUP_NOTIFY:-no}"
   local _SERVER="${NOTES_SERVER_NAME}"
   local _PORT=${NOTES_SERVER_PORT}
   local _PATH="$NOTES_TMP_FILE"
   __netcat_test
   printf_green "Attempting to send message to $_SERVER on $_PORT"
-  printf "%s\n" "$*" >"${_PATH}" 2>>$NOTES_TMPDIR/notes_client
-  cat "$_PATH" 2>>$NOTES_TMPDIR/notes_client | __nc_send "$_SERVER" "$_PORT" 2>>$NOTES_TMPDIR/notes_client || __failed
-  if [ "$NOTES_NOTIFY" = "yes" ]; then
-    [ $? = 0 ] && _notifications "New note" "$(cat $_PATH)\nPosted to: ${NOTES_PATH}" || \
-      _notifications "NotesCLI" "Sending of note failed"
+  if printf "%s\n" "$*" >"$_PATH" 2>>$NOTES_TMPDIR/notes_client &&
+    cat "$_PATH" 2>>$NOTES_TMPDIR/notes_client | __nc_send "$_SERVER" "$_PORT" 2>>$NOTES_TMPDIR/notes_client; then
+    __dedup "$MESSAGE" "$NOTES_PATH"
+    __success "NotesCLI"
+    exitCode=0
+  else
+    __failed "NotesCLI"
+    exitCode=1
   fi
-  __local && __sync_tmp "$NOTES_PATH" "$_PATH"
+  if [ ${exitCode:-$?} = 0 ]; then
+    if [ "$NOTES_NOTIFY" = "yes" ]; then
+      if [ -z "$DEDUP" ]; then
+        _notifications "New note" "$(cat $_PATH)\nPosted to: $NOTES_PATH"
+      fi
+    else
+      _notifications "NotesCLI" "Sending of note failed"
+    fi
+  fi
+  if [ -z "$DEDUP" ]; then
+    __local && __sync_tmp "$NOTES_PATH" "$_PATH"
+  fi
   rm -Rf "$_PATH"
   return "$?"
 }
@@ -316,9 +359,9 @@ __run_sync() {
 # list all notes
 __list_all() {
   printf_green "All notes in $NOTES_DIRECTORY"
-  find ${NOTES_DIRECTORY}/*/* ${NOTES_DIRECTORY}/all.txt -type f -iname "*.txt" -not -path "${NOTES_DIRECTORY}/archive/*" | \
-    sed 's#'$NOTES_DIRECTORY/'##g' | \
-    __column | \
+  find ${NOTES_DIRECTORY}/*/* ${NOTES_DIRECTORY}/all.txt -type f -iname "*.txt" -not -path "${NOTES_DIRECTORY}/archive/*" |
+    sed 's#'$NOTES_DIRECTORY/'##g' |
+    __column |
     printf_read "6"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -362,11 +405,15 @@ case "$1" in
     exit $?
   fi
   if [ "$2" = "--kill" ]; then
-    printf_red "Starting shutdown"
-    shift 1
-    touch "$NOTES_TMPDIR/kill_notes"
-    __netcat_kill_server "$NOTES_SERVER_PORT" "printf_green" "printf_red"
+    if netstatg "$NOTES_SERVER_PORT" &>/dev/null; then
+      printf_red "Starting shutdown"
+      shift 1
+      touch "$NOTES_TMPDIR/kill_notes"
+      __netcat_kill_server "$NOTES_SERVER_PORT" "printf_green" "printf_red"
     #kill -s 9 "$(netstatg $NOTES_SERVER_PORT | awk '{print $7}' | head -n 1 | sed 's#/.*##g')" || true
+    else
+      printf_red "Server is not running"
+    fi
     exit $?
   fi
 
@@ -414,14 +461,18 @@ case "$1" in
         export NOTES_SERVER_NAME NOTES_SERVER_PORT NOTES_SERVER_DIRECTORY NOTES_LOG_FILE NOTES_TMP_FILE NOTES_SERVER_PATH
         ;;
       *stop)
-        __system_service_exists notes_server.service && printf_exit 2 0 "Notes server is not installed"
         shift 3
+        __system_service_exists notes_server.service && printf_exit 2 0 "Notes server is not installed"
         touch "$NOTES_TMPDIR/kill_notes"
         __netcat_kill_server "$NOTES_SERVER_PORT"
         ;;
       *-start)
-        __system_service_exists notes_server.service && printf_exit 2 0 "Notes server is not installed"
         shift 3
+        __system_service_exists notes_server.service && printf_exit 2 0 "Notes server is not installed"
+        if [ "$1" = "--loop" ]; then
+          shift 1
+          NOTES_SERVER_LOOP="yes"
+        fi
         opts="$*"
         __run_service "$opts" 2>>"$NOTES_LOG_FILE"
         ;;
@@ -451,21 +502,28 @@ case "$1" in
   # End Systemd
 
   *start)
-    shift 1
-    printf_green "Starting notes server for $USER"
-    __server &>/dev/null
+    shift 2
+    if [ "$1" = "--loop" ]; then
+      NOTES_SERVER_LOOP=yes
+      shift 1
+    else
+      printf_green "Starting notes server for $USER"
+      printf_newline
+    fi
+    __server "$@" &>/dev/null
     sleep 3
     ;;
 
   *enable)
+    shift 2
     __server_enable
     ;;
 
   *edit)
-    shift 1
-    if [ "$2" = prev ]; then
+    shift 2
+    if [ "$1" = prev ]; then
       ssh -qt "$NOTES_SERVER_NAME" notes open "$NOTES_PREV_FILE"
-    elif [ "$2" = "all" ]; then
+    elif [ "$1" = "all" ]; then
       ssh -qt "$NOTES_SERVER_NAME" notes all
     else ssh -qt "$NOTES_SERVER_NAME" notes; fi
     __run_sync
@@ -546,7 +604,7 @@ search)
   search_results="$(cat "$NOTES_DIRECTORY/all.txt" "$NOTES_PREV_FILE" "$NOTES_PATH" | grep -i "$1" 2>/dev/null)"
   if [ -n "$search_results" ]; then
     printf_green "Search results: "
-    echo "$search_results" | printf_readline "7";
+    echo "$search_results" | printf_readline "7"
     exitCode=0
   else
     printf_red "No results found"
@@ -567,8 +625,8 @@ search)
       __update_notes "$message" "${NOTES_PATH}"
     fi
   else
-      message="$*"
-      __update_notes "$message" "${NOTES_PATH}"
+    message="$*"
+    __update_notes "$message" "${NOTES_PATH}"
   fi
   ;;
 
@@ -581,8 +639,8 @@ search)
       __notes
     fi
   else
-      message="$*"
-      __update_notes "$message" "${NOTES_PATH}"
+    message="$*"
+    __update_notes "$message" "${NOTES_PATH}"
   fi
   __run_sync
   ;;
