🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/run_server b/bin/run_server
--- a/bin/run_server
+++ b/bin/run_server
@@ -41,36 +41,56 @@ user_install
 __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __test_server() { netstatg $1 | grep -qi python && return 0 || return 1; }
+__return_error() { printf '%s\n' "Failed to start server" &>>"$SERVER_LOG" && printf_exit 1 1 "Failed to start the server"; }
+__python3_serv() { python3 -m http.server --cgi --bind "$myip" "${port}" &>>"$SERVER_LOG" && echo Py3 started &>>"$SERVER_LOG" || return 1; }
+__python2_serv() { python2 -m http.server --cgi --bind "$myip" "${port}" &>>"$SERVER_LOG" && echo Py2 started &>>"$SERVER_LOG" || return 1; }
+__py_simple() { python -m SimpleHTTPServer "${port}" &>>"$SERVER_LOG" && echo "Py simple start" &>>"$SERVER_LOG" || return 1; }
+__default_srv() {
+  python2 -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' &>>"$SERVER_LOG" && echo "Default has started" || return 1
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 open_url() {
-  if __cmd_exists "xdg-open"; then
+  if cmd_exists "xdg-open"; then
     xdg-open "$1"
-  elif __cmd_exists "open"; then
+  elif cmd_exists "open"; then
     open "$1"
   fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 run_server() {
+  if [ "$1" = "--bg" ]; then
+    shift 1
+    echo "launching background process"
+    SERVER_LOG="${TMPDIR:-/tmp}/run_server_bg.log"
+    $APPNAME "$*" &>"$SERVER_LOG" &
+    disown
+    exit $?
+  fi
   local i=0
-  local port="${1:-8000}"
+  local port="${1:-8000}" && shift
   local myip=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}')
   local MAX_NUMBER_OF_TRIES=10
+  local TMP_DIR="${TMPDIR:-/tmp}"
+  local SERVER_LOG="${SERVER_LOG:-$TMPDIR/run_server_$port.log}"
 
   printf_yellow "Access from the network: http://$myip:$port"
   printf_red "control-c to exit"
+  echo >"$SERVER_LOG"
+
   while [ $i -lt $MAX_NUMBER_OF_TRIES ]; do
     if [ "$(__test_server $port)" != "" ]; then
-      open_url "http://$myip:${port}/"
+      port="$i"
       break
     fi
     i=$((i + 1))
     sleep 1
-  done &
+  done
 
-  __devnull python3 -m http.server --cgi --bind "$myip" "${port}" ||
-    __devnull python2 -m http.server --cgi --bind "$myip" "${port}" ||
-    __devnull python -m SimpleHTTPServer "${port}" ||
-    printf_exit 1 1 "Failed to start the server"
+  printf '%s\n' "Starting the server on port $port" &>>"$SERVER_LOG"
+  __default_srv || __python3_serv || __python2_serv || __py_simple || __return_error
+  sleep 10
+  printf "%s\n" "Process id is $(netstatl | grep $port | awk '{print $7}')" &>>"$SERVER_LOG"
+  open_url "http://$myip:${port}/"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 run_server "$@"
