🐛 FIXED: Notes I think 🐛

diff --git a/notes b/notes
--- a/notes
+++ b/notes
@@ -11,52 +11,49 @@ USER="${SUDO_USER:-${USER}}"
 # @Created     : Wed, Aug 05, 2020, 02:00 EST
 # @License     : WTFPL
 # @Copyright   : Copyright (c) CasjaysDev
-# @Description : take notes using bash
+# @Description : Take notes using bash
 #
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
 # Set functions
-
 SCRIPTSFUNCTURL="${SCRIPTSAPPFUNCTURL:-https://github.com/dfmgr/installer/raw/master/functions}"
 SCRIPTSFUNCTDIR="${SCRIPTSAPPFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}"
 SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-testing.bash}"
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
 if [ -f "$PWD/functions/$SCRIPTSFUNCTFILE" ]; then
   . "$PWD/functions/$SCRIPTSFUNCTFILE"
 elif [ -f "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE" ]; then
   . "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE"
 fi
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 user_install
 __options "$@"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-NOTES_NOTIFY="yes"
-NOTES_TMPDIR="${TMP:-/tmp}"
 NOTES_FOLDER="$(date +%Y)"
 NOTES_FILE="$(date +%m).txt"
 NOTES_PREV_MONTH="$(date --date="1 Month Ago" +%m).txt"
-NOTES_DIRECTORY="${NOTES_DIRECTORY:-"$HOME/.local/share/editors/notes"}"
 NOTES_EDITOR="${NOTES_EDITOR:-vim}"
-NOTES_SERVER_NAME="${NOTES_SERVER_NAME:-localhost}"
+NOTES_TMPDIR="${TMPDIR:-/tmp}/notes"
+NOTES_DIRECTORY="${NOTES_DIRECTORY:-$HOME/.local/share/editors/notes}"
+NOTES_SERVER_NAME="${NOTES_SERVER_NAME:-}"
 NOTES_SERVER_PORT="${NOTES_SERVER_PORT:-65000}"
 NOTES_SERVER_DIRECTORY="$NOTES_DIRECTORY"
 NOTES_LOG_FILE="${NOTES_TMPDIR}/notes_server.log"
 NOTES_TMP_FILE="$(mktemp $NOTES_TMPDIR/notes.XXXXXX.txt 2>/dev/null)"
 NOTES_PATH="$NOTES_DIRECTORY/$NOTES_FOLDER/$NOTES_FILE"
+NOTES_ALL_PATH="$NOTES_DIRECTORY/all.txt"
 NOTES_SERVER_PATH="$NOTES_SERVER_DIRECTORY/$NOTES_FOLDER/$NOTES_FILE"
 NOTES_PREV_FILE="$NOTES_SERVER_DIRECTORY/$NOTES_FOLDER/$NOTES_PREV_MONTH"
 NOTES_NOTIFY="${NOTES_NOTIFY:-yes}"
 
 netcat="$(command -v nc 2>/dev/null || command -v netcat 2>/dev/null)"
 
-[ -f "$HOME/.config/notes/config" ] && . "$HOME/.config/notes/config"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+[ -f "$HOME/.config/notes/settings" ] && . "$HOME/.config/notes/settings"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [ ! -f "$NOTES_DIRECTORY/tmux.conf" ]; then
-  cat <<EOF >"$NOTES_DIRECTORY/tmux.conf"
+tmux() {
+  if [ ! -f "$NOTES_DIRECTORY/tmux.conf" ]; then
+    cat <<EOF >"$NOTES_DIRECTORY/tmux.conf"
 # Very basic tmux config
 unbind C-b
 set-option -g prefix C-a
@@ -83,25 +80,32 @@ setw -g window-status-style 'fg=colour9 bg=colour18'
 setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '
 setw -g window-status-bell-style 'fg=colour255 bg=colour1 bold'
 set -g message-style 'fg=colour232 bg=colour16 bold'
+
 EOF
-fi
+  fi
+}
 
 gen_config() {
   __mkd "$HOME/.config/notes"
   echo 'NOTES_FOLDER="$(date +%Y)"
+NOTES_FOLDER="$(date +%Y)"
 NOTES_FILE="$(date +%m).txt"
-NOTES_TMPDIR="'${TMP:-/tmp}'"
+NOTES_PREV_MONTH="$(date --date="1 Month Ago" +%m).txt"
+NOTES_EDITOR="${NOTES_EDITOR:-vim}"
+NOTES_TMPDIR="${NOTES_TMPDIR:-/tmp}/notes"
 NOTES_DIRECTORY="'${NOTES_DIRECTORY:-"$HOME/.local/share/editors/notes"}'"
-NOTES_EDITOR="'${NOTES_EDITOR:-vim}'"
-NOTES_SERVER_NAME="'${NOTES_SERVER_NAME:-localhost}'"
+NOTES_SERVER_NAME="'${NOTES_SERVER_NAME:-}'"
 NOTES_SERVER_PORT="'${NOTES_SERVER_PORT:-65000}'"
-NOTES_SERVER_DIRECTORY="'${NOTES_DIRECTORY}'"
+NOTES_SERVER_DIRECTORY="'$NOTES_DIRECTORY'"
 NOTES_LOG_FILE="'${NOTES_TMPDIR}/notes_server.log'"
-NOTES_TMP_FILE="$(mktemp ${NOTES_TMPDIR}/notes.XXXXXX.txt 2>/dev/null)"
-NOTES_PATH="${NOTES_DIRECTORY}/${NOTES_FOLDER}/${NOTES_FILE}"
-NOTES_SERVER_PATH="${NOTES_SERVER_DIRECTORY}/${NOTES_FOLDER}/${NOTES_FILE}"
-NOTES_NOTIFY="${NOTES_NOTIFY:-yes}"
-' >"$HOME/.config/notes/config"
+NOTES_TMP_FILE="$(mktemp $NOTES_TMPDIR/notes.XXXXXX.txt 2>/dev/null)"
+NOTES_PATH="'$NOTES_DIRECTORY/$NOTES_FOLDER/$NOTES_FILE'"
+NOTES_ALL_PATH="'$NOTES_DIRECTORY/all.txt'"
+NOTES_SERVER_PATH="'$NOTES_SERVER_DIRECTORY/$NOTES_FOLDER/$NOTES_FILE'"
+NOTES_PREV_FILE="$NOTES_SERVER_DIRECTORY/$NOTES_FOLDER/$NOTES_PREV_MONTH"
+NOTES_NOTIFY="'${NOTES_NOTIFY:-yes}'"
+' >"$HOME/.config/notes/settings"
+  #[ -f "$HOME/.config/notes/settings" ] && . "$HOME/.config/notes/settings"
 }
 
 systemd_service() {
@@ -117,18 +121,18 @@ Type=dbus
 Restart=always
 RestartSec=5
 KillMode=mixed
-User='${USER:-daemon}'
-Group='${USER:-daemon}'
+User='"${USER:-daemon}"'
+Group='"${USER:-daemon}"'
 
-Environment=HOME='${HOME}'
-Environment=TERM='${TERM:-linux}'
-Environment=NOTES_TMPDIR='${TMP:-/tmp/notes_server}'
-Environment=NOTES_DIRECTORY='${HOME}/.local/share/editors/notes'
-Environment=NOTES_LOG_FILE='${NOTES_TMPDIR}/notes_server.log'
+Environment=HOME='"${HOME}"'
+Environment=TERM='"${TERM:-linux}"'
+Environment=NOTES_TMPDIR='"${TMP:-/tmp/notes_server}"'
+Environment=NOTES_DIRECTORY='"${HOME}/.local/share/editors/notes"'
+Environment=NOTES_LOG_FILE='"${NOTES_TMPDIR}/notes_server.log"'
 Environment=NOTES_SERVER_NAME="$(hostname -f)"
 Environment=NOTES_SERVER_PORT=65000
 Environment=NOTES_TMP_FILE="$(mktemp $NOTES_TMPDIR/notes.XXXXXX.txt 2>/dev/null)"
-Environment=NOTES_NOTIFY="'${NOTES_NOTIFY:-yes}'"
+Environment=NOTES_NOTIFY='"${NOTES_NOTIFY:-yes}"'
 
 ExecStartPre=/usr/local/bin/notes server systemd run vars
 ExecStopPost=/usr/bin/rm -Rf "$NOTES_TMPDIR $NOTES_LOG_FILE"
@@ -171,23 +175,44 @@ EOF
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 _debug() {
-  echo $NOTES_FOLDER $NOTES_FILE $NOTES_TMPDIR $NOTES_DIRECTORY $NOTES_EDITOR $NOTES_SERVER_NAME $NOTES_SERVER_PORT $NOTES_SERVER_DIRECTORY $NOTES_LOG_FILE $NOTES_TMP_FILE $NOTES_PATH $NOTES_SERVER_PATH
+  echo "NOTES_FOLDER:$NOTES_FOLDER" "NOTES_FILE:$NOTES_FILE"
+  echo "NOTES_TMPDIR:$NOTES_TMPDIR" "NOTES_DIRECTORY:$NOTES_DIRECTORY"
+  echo "NOTES_EDITOR:$NOTES_EDITOR" "NOTES_SERVER_NAME:$NOTES_SERVER_NAME"
+  echo "NOTES_SERVER_PORT:$NOTES_SERVER_PORT" "NOTES_SERVER_DIRECTORY:$NOTES_SERVER_DIRECTORY"
+  echo "NOTES_LOG_FILE:$NOTES_LOG_FILE" "NOTES_TMP_FILE:$NOTES_TMP_FILE"
+  echo "NOTES_PATH:$NOTES_PATH" "NOTES_SERVER_PATH:$NOTES_SERVER_PATH"
+  exit
 }
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __netcat_test() { __cmd_exists $netcat || printf_exit "The program netcat is not installed"; }
 __nc_send() { $netcat -c $1 $2 2>>"$NOTES_LOG_FILE" && true || $netcat -w 1 $1 $2 2>>"$NOTES_LOG_FILE" || return 1; }
-__notes() { eval tmux -f "${NOTES_DIRECTORY}/tmux.conf" new-session -D -A -s notes "vim ${1:-$NOTES_PATH}" &>/dev/null; }
+__notes() { eval tmux -f "$NOTES_DIRECTORY/tmux.conf" new-session -D -A -s notes vim ${1:-$NOTES_PATH} &>/dev/null || return 1; }
+__local() { if [ "$NOTES_SERVER_NAME" = "$(hostname -f)" ] || [ "$NOTES_SERVER_NAME" = "localhost" ]; then return 1; else return 0; fi; }
 __dedupe() { cat "$1" | grep -v "$2"; }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-__sync() {
-  local _NOTESA="${1:-$NOTES_DIRECTORY}"
-  local _NOTESP="${2:-$NOTES_PATH}"
-  local _TPATH="${3:-$_PATH}"
-  [ -n "$_TPATH" ] && cat "${_NOTESP}" "$_TPATH" >"$NOTES_TMPDIR/notes_cli.tmp" && mv -f "$NOTES_TMPDIR/notes_cli.tmp" "${_NOTESP}"
-  cat "${_NOTESP}" "${_NOTESA}/all.txt" | sort -u | sed '/^\#/d;/^$/d' >"$NOTES_TMPDIR/notes_cli.tmp" && mv -f "$NOTES_TMPDIR/notes_cli.tmp" "${_NOTESA}/all.txt"
-  [ -f "$NOTES_TMPDIR/notes_cli.tmp" ] && rm -Rf "$NOTES_TMPDIR/notes_cli.tmp"
-  return 0
+
+__sync_tmp() {
+  local _NOTESP="${1:-$NOTES_PATH}"
+  local _TPATH="${2:-$_PATH}"
+  if [ -n "$_TPATH" ]; then cat "$_NOTESP" "$_TPATH" >"$NOTES_TMPDIR/notes_cli.tmp" && __mv_f "$NOTES_TMPDIR/notes_cli.tmp" "$_NOTESP"; fi
+}
+__sync_all() {
+  local exitCode=0
+  local _NOTESP="${1:-$NOTES_PATH}"
+  local _NOTESA="${2:-$NOTES_ALL_PATH}"
+  #printf_green "Syncing $_NOTESP:"
+  #printf_green "to $_NOTESA"
+  [ -s "$_NOTESA" ] || touch "$_NOTESP"
+  if [ ! -s "$_NOTESP" ]; then
+    cat "$_NOTESP" | tee "$_NOTESA" &>/dev/null
+    cat "$_NOTESP" "$_NOTESA" | sort -u | sed '/^\#/d;/^$/d' >"$NOTES_TMPDIR/notes_cli.tmp" || local exitCode=1
+  fi
+  if [ -f "$NOTES_TMPDIR/notes_cli.tmp" ]; then __mv_f "$NOTES_TMPDIR/notes_cli.tmp" "$_NOTESA" || local exitCode=1; fi
+  if [ -f "$NOTES_TMPDIR/notes_cli.tmp" ]; then __rm_rf "$NOTES_TMPDIR/notes_cli.tmp" && sleep 1 || local exitCode=1; fi
+  #[ "$exitCode" = 0 ] && printf_green "Sync completed" || printf_error 1 "Sync failed"
+  #return "$exitCode"
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -253,19 +278,26 @@ __client() {
   printf_green "Attempting to send message to $_SERVER on $_PORT"
   printf "%s\n" "$*" >"${_PATH}" 2>>$NOTES_TMPDIR/notes_client
   cat "$_PATH" 2>>$NOTES_TMPDIR/notes_client | __nc_send "$_SERVER" "$_PORT" 2>>$NOTES_TMPDIR/notes_client &&
+    cat "$_PATH" >>$NOTES_PATH &&
     notifications "New note" "$(cat $_PATH)\nPosted to: ${NOTES_PATH}" || __failed
-  __sync "$NOTES_PATH" "$NOTES_DIRECTORY" "$_PATH"
+  __local && __sync_tmp "$NOTES_PATH" "$_PATH"
   rm -Rf "$_PATH"
   return "$?"
 }
 
 __import() {
-  [ -f "$NOTES_PREV_FILE" ] && cat "$NOTES_PREV_FILE" | sed '/^\#/d;/^$/d' >>"${NOTES_PATH}" || return 1
-  printf_green "Notes have been imported"
+  if [ -f "$NOTES_PREV_FILE" ]; then
+    cat "$NOTES_PREV_FILE" | sed '/^\#/d;/^$/d' >>"${NOTES_PATH}"
+    printf_green "Notes have been imported"
+  fi
+  exit $?
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-mkdir -p "${NOTES_DIRECTORY}/$NOTES_FOLDER"
+__mkd "$NOTES_TMPDIR" "${NOTES_DIRECTORY}/$NOTES_FOLDER"
+touch "$NOTES_ALL_PATH"
+tmux
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Previous month
 if [ ! -f "$NOTES_PATH" ]; then
@@ -274,146 +306,138 @@ if [ ! -f "$NOTES_PATH" ]; then
     printf_green "You can do it manually by running $APPNAME --import"
   else
     printf_green "Assuming its a new month: importing unfinished notes"
-    echo -e "## Notes for $(date +%B) created on $(date +"%D at %H:%M") ##\n" >"${NOTES_PATH}"
+    echo -e "## Notes for $(date +"%B %Y") created on $(date +"%D at %H:%M") ##\n" >"${NOTES_PATH}"
     __import && sleep 3
   fi
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-case $1 in
---import)
-  shift 1
-  __import
-  exit $?
-  ;;
-esac
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 case "$1" in
-*server | *service)
-  if [ "$2" = "--help" ]; then shift 1 && printf_help 'Usage: notes server  |  Start the server'; fi
-  if [ "$2" = "--status" ]; then
-    shift 1
-    netstatg "$NOTES_SERVER_PORT" 2>/dev/null | printf_readline
-    exit 0
-  fi
-  if [ "$2" = "--kill" ]; then
-    printf_red "Starting shutdown"
-    shift 1
-    touch "$NOTES_TMPDIR/kill_notes"
-    __netcat_kill_server "$NOTES_SERVER_PORT" "printf_green" "printf_red"
-    #kill -s 9 "$(netstatg $NOTES_SERVER_PORT | awk '{print $7}' | head -n 1 | sed 's#/.*##g')" || true
-    exit $?
-  fi
-
-  # begin systemd 2 ddep
-  case "$2" in
-  *systemd)
+server | service)
+  shift 1
+  # begin systemd 2 deep
+  case "$1" in
+  systemd)
     shift 1
     case $2 in
-    *install)
-      shift 2
+    install)
+      shift 1
       NOTES_DIRECTORY="$NOTES_SERVER_DIRECTORY"
       systemd_service "/etc/systemd/system/notes_server.service" &&
         __devnull sudo systemctl daemon-reload &&
         __devnull sudo systemctl start notes_server &&
         __devnull sudo systemctl enable -f notes_server && printf_green "Service has been created" || printf_red "Failed to create service"
       ;;
-    *remove)
-      shift 2
+    remove)
+      shift 1
       __system_service_exists notes_server.service || printf_exit 1 0 "Notes server is not installed"
       __devnull sudo systemctl disable -f notes_server &&
         __devnull sudo systemctl daemon-reload &&
         __rm_rf /etc/systemd/system/notes_server.service && printf_green "Service has been deleted" || printf_red "Failed to delete service"
       ;;
-    *-start)
-      shift 2
+    start)
+      shift 1
       __system_service_exists notes_server.service || printf_exit 2 0 "Notes server is not installed"
       __devnull sudo systemctl start notes_server && printf_green "Service has been started" || printf_red "Failed to start service"
       ;;
-    *stop)
-      shift 2
+    stop)
+      shift 1
       __system_service_exists notes_server.service || printf_exit 2 0 "Notes server is not installed"
       __devnull sudo systemctl stop notes_server && printf_green "Service has been stopped" || printf_red "Failed to stop service"
       ;;
-    *restart)
-      shift 2
+    restart)
+      shift 1
       __system_service_exists notes_server.service || printf_exit 2 0 "Notes server is not installed"
       __devnull sudo systemctl restart notes_server && printf_green "Service has been restarted" || printf_red "Failed to restart service"
       ;;
-    *run)
-      case $3 in
-      *vars)
-        shift 3
+    run)
+      shift 1
+      case $1 in
+      vars)
+        shift 1
         __system_service_exists notes_server.service && printf_exit 2 0 "Notes server is not installed"
         export NOTES_NOTIFY NOTES_FOLDER NOTES_FILE NOTES_TMPDIR NOTES_DIRECTORY NOTES_EDITOR NOTES_PATH
         export NOTES_SERVER_NAME NOTES_SERVER_PORT NOTES_SERVER_DIRECTORY NOTES_LOG_FILE NOTES_TMP_FILE NOTES_SERVER_PATH
         ;;
-      *stop)
+      stop)
         __system_service_exists notes_server.service && printf_exit 2 0 "Notes server is not installed"
-        shift 3
+        shift 1
         touch "$NOTES_TMPDIR/kill_notes"
         __netcat_kill_server "$NOTES_SERVER_PORT"
         ;;
-      *-start)
+      start)
         __system_service_exists notes_server.service && printf_exit 2 0 "Notes server is not installed"
-        shift 3
-        opts="$*"
+        shift 1
+        opts="$"
         __run_service "$opts" 2>>"$NOTES_LOG_FILE"
         ;;
-      *restart)
+      restart)
         __system_service_exists notes_server.service && printf_exit 2 0 "Notes server is not installed"
-        shift 3
-        opts="$*"
+        shift 1
+        opts="$"
         touch "$NOTES_TMPDIR/kill_notes"
         __netcat_kill_server "$NOTES_SERVER_PORT"
         __run_service "$opts" 2>>"$NOTES_LOG_FILE"
         ;;
       *)
         __system_service_exists notes_server.service && printf_exit 2 0 "Notes server is not installed"
-        shift 2
         opts="$*"
         __run_service "$opts" 2>>"$NOTES_LOG_FILE"
         ;;
       esac
       ;;
-    status | *)
-      shift 2
+    status)
+      shift
       __system_service_exists notes_server.service || printf_exit 2 0 "Notes server is not installed"
       sudo systemctl status notes_server | printf_readline "255"
       ;;
+    *) ;;
     esac
+    # End Systemd
     ;;
-  # End Systemd
 
-  *start)
+  start)
     shift 1
     printf_green "Starting notes server for $USER"
     __server &>/dev/null
     sleep 3
     ;;
-  *enable)
+  enable)
+    shift 1
     __server_enable
     ;;
-  *open)
+  open)
     shift 1
     [ "$2" = "all" ] && ssh -qt "$NOTES_SERVER_NAME" notes all || ssh -qt "$NOTES_SERVER_NAME" notes
     ;;
 
   *)
-    shift 1
+    if [ "$2" = "--help" ]; then shift 1 && printf_help 'Usage: notes server  |  Start the server'; fi
+    if [ "$2" = "--status" ]; then
+      shift 1
+      netstatg "$NOTES_SERVER_PORT" 2>/dev/null | printf_readline
+      exit 0
+    fi
+    if [ "$2" = "--kill" ]; then
+      printf_red "Starting shutdown"
+      shift 1
+      touch "$NOTES_TMPDIR/kill_notes"
+      __netcat_kill_server "$NOTES_SERVER_PORT" "printf_green" "printf_red"
+      #kill -s 9 "$(netstatg $NOTES_SERVER_PORT | awk '{print $7}' | head -n 1 | sed 's#/.##g')" || true
+      exit $?
+    fi
     opts="$*"
     __server "$opts" 2>>"$NOTES_LOG_FILE"
     ;;
   esac
   ;;
 
-*client)
+client)
   shift 1
   [ "$1" = "--help" ] && printf_help 'Usage: notes client "my message"  |  Send your notes to the server'
   [ -n "$NOTES_SERVER_NAME" ] || printf_help "Please set NOTES_SERVER_NAME variable to your server"
   if [ ${#} -eq 0 ]; then
     if [ -p "/dev/stdin" ]; then
-      message="$(cat </dev/stdin)"
+      message="$(</dev/stdin)"
     fi
   else
     message="$*"
@@ -423,32 +447,39 @@ case "$1" in
     notifications "$APPNAME" "failed to send to $NOTES_SERVER_NAME"
   ;;
 
-*open)
+open)
   shift 1
   if [ $# = 0 ]; then
-    ls -A ${NOTES_DIRECTORY}/*/* | sed 's#"##g' | sort -u | printf_readline "6"
+    find "${NOTES_DIRECTORY}" -type f | sed 's#"##g' | sort -u | printf_readline "6"
   else
-    __notes "$@" 2>/dev/null
+    __notes "${1}" 2>/dev/null
   fi
+  ;;
+
+\
+  all)
+  shift 1
+  __notes "${NOTES_ALL_PATH}"
+  ;;
+
+config)
+  shift 1
+  gen_config && printf_green "config file was created in ~/.config/notes/settings"
+  ;;
+
+import)
+  shift 1
+  __import
+  ;;
+
+show)
+  shift 1
+  [ -f "$NOTES_PATH" ] && cat "$NOTES_PATH" 2>/dev/null | printf_readline "5" || printf_exit ""
   ;;
 
 -)
   shift 1
   printf "%s\n" "$(</dev/stdin)" >>"${NOTES_PATH}"
-  ;;
-
-*all)
-  shift 1
-  __notes "${NOTES_DIRECTORY}/all.txt"
-  ;;
-
-*config)
-  shift 1
-  gen_config && printf_green "config file was created in ~/.config/notes/config"
-  ;;
-
-*show)
-  [ -f "$NOTES_PATH" ] && cat "$NOTES_PATH" 2>/dev/null | printf_readline "5" || printf_exit ""
   ;;
 
 *)
@@ -463,12 +494,12 @@ case "$1" in
   else
     printf "%s\n" "${*}" >>"${NOTES_PATH}"
   fi
-  __sync "$NOTES_DIRECTORY" "$NOTES_PATH" 2>/dev/null &&
+  __sync "$NOTES_PATH" "$NOTES_ALL_PATH" 2>/dev/null &&
     [ $? = 0 ] && notifications "New note" "Posted to: ${NOTES_PATH}"
   ;;
 
 esac
-
+__rm_rf "$NOTES_TMP_FILE"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit $?
 # end
