🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/templates/scripts/bash/bash b/templates/scripts/bash/bash
--- a/templates/scripts/bash/bash
+++ b/templates/scripts/bash/bash
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 APPNAME="$(basename $0)"
+VERSION="GEN_SCRIPTS_REPLACE_VERSION"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
@@ -8,56 +9,102 @@ SRC_DIR="${BASH_SOURCE%/*}"
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : GEN_SCRIPT_REPLACE_VERSION
-# @Author        : GEN_SCRIPT_REPLACE_AUTHOR
-# @Contact       : GEN_SCRIPT_REPLACE_EMAIL
-# @License       : GEN_SCRIPT_REPLACE_LICENSE
-# @ReadME        : GEN_SCRIPT_REPLACE_FILENAME --help
-# @Copyright     : GEN_SCRIPT_REPLACE_COPYRIGHT
-# @Created       : GEN_SCRIPT_REPLACE_DATE
-# @File          : GEN_SCRIPT_REPLACE_FILENAME
-# @Description   : GEN_SCRIPT_REPLACE_DESC
-# @TODO          : GEN_SCRIPT_REPLACE_TODO
-# @Other         : GEN_SCRIPT_REPLACE_OTHER
-# @Resource      : GEN_SCRIPT_REPLACE_RES
+##@Version       : GEN_SCRIPTS_REPLACE_VERSION
+# @Author        : GEN_SCRIPTS_REPLACE_AUTHOR
+# @Contact       : GEN_SCRIPTS_REPLACE_EMAIL
+# @License       : GEN_SCRIPTS_REPLACE_LICENSE
+# @ReadME        : GEN_SCRIPTS_REPLACE_FILENAME --help
+# @Copyright     : GEN_SCRIPTS_REPLACE_COPYRIGHT
+# @Created       : GEN_SCRIPTS_REPLACE_DATE
+# @File          : GEN_SCRIPTS_REPLACE_FILENAME
+# @Description   : GEN_SCRIPTS_REPLACE_DESC
+# @TODO          : GEN_SCRIPTS_REPLACE_TODO
+# @Other         : GEN_SCRIPTS_REPLACE_OTHER
+# @Resource      : GEN_SCRIPTS_REPLACE_RES
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Import functions
-CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
-SCRIPTSFUNCTDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}/functions"
-SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-testing.bash}"
-SCRIPTSFUNCTURL="${SCRIPTSAPPFUNCTURL:-https://github.com/dfmgr/installer/raw/master/functions}"
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [ -f "$PWD/$SCRIPTSFUNCTFILE" ]; then
-  . "$PWD/$SCRIPTSFUNCTFILE"
-elif [ -f "$SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE" ]; then
-  . "$SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE"
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
 else
-  echo "Can not load the functions file: $SCRIPTSFUNCTDIR/$SCRIPTSFUNCTFILE" 1>&2
-  exit 1
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
 fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# user system devenv dfmgr dockermgr fontmgr iconmgr pkmgr systemmgr thememgr wallpapermgr
-user_install
-__options "$@"
+# Default directories
+GEN_SCRIPTS_ARRAY_DIR="$HOME/.local/share/CasjaysDev/arrays/GEN_SCRIPTS_REPLACE_FILENAME"
+GEN_SCRIPTS_REPLACE_CONFDIR="$HOME/.config/GEN_SCRIPTS_REPLACE_FILENAME"
+GEN_SCRIPTS_REPLACE_CONFFILE="settings.conf"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Check for needed applications
-__cmd_exists bash || exit 1 # exit 1 if not found
+# helper function
+__version() { app_version; }
+__list_array() { mkdir -p "$GEN_SCRIPTS_ARRAY_DIR" && __list_options >"$GEN_SCRIPTS_ARRAY_DIR/array" && exit; }
+__list_options() { echo -n "-$SHORTOPTS " | sed 's#:##g;s#,# -#g' && echo "--$LONGOPTS " | sed 's#:##g;s#,# --#g' && exit; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Set variables
+__help() {
+  app_help "Usage: GEN_SCRIPTS_REPLACE_FILENAME  -  GEN_SCRIPTS_REPLACE_FILENAME --version" \
+    "-c, --config           -  create config file" \
+    "-a, --all              -  show all options" \
+    "-l, --list             -  used by completions" \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
+  exit
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+__gen_config() {
+  printf_green "Generating the config file in"
+  printf_green "$GEN_SCRIPTS_REPLACE_CONFDIR/$GEN_SCRIPTS_REPLACE_CONFFILE"
+  [ -d "$GEN_SCRIPTS_REPLACE_CONFDIR" ] || mkdir -p "$GEN_SCRIPTS_REPLACE_CONFDIR"
+  [ -f "$GEN_SCRIPTS_REPLACE_CONFDIR/$GEN_SCRIPTS_REPLACE_CONFFILE" ] &&
+    cp -Rf "$GEN_SCRIPTS_REPLACE_CONFDIR/$GEN_SCRIPTS_REPLACE_CONFFILE" "$GEN_SCRIPTS_REPLACE_CONFDIR/$GEN_SCRIPTS_REPLACE_CONFFILE.$$"
+  cat <<EOF >"$GEN_SCRIPTS_REPLACE_CONFDIR/$GEN_SCRIPTS_REPLACE_CONFFILE"
+# Settings for GEN_SCRIPTS_REPLACE_FILENAME
 
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Set functions
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Set additional variables
-
+EOF
+  if [ -f "$GEN_SCRIPTS_REPLACE_CONFDIR/$GEN_SCRIPTS_REPLACE_CONFFILE" ]; then
+    printf_green "Your config file for GEN_SCRIPTS_REPLACE_FILENAME has been created"
+  else printf_red "Failed to create the config file"; fi
+  exit $?
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # bring in user config
-[ -f "$HOME/.config/GEN_SCRIPT_REPLACE_FILENAME/settings" ] &&
-  . "$HOME/.config/GEN_SCRIPT_REPLACE_FILENAME/settings"
+[ -f "$GEN_SCRIPTS_REPLACE_CONFDIR/$GEN_SCRIPTS_REPLACE_CONFFILE" ] && . "$GEN_SCRIPTS_REPLACE_CONFDIR/$GEN_SCRIPTS_REPLACE_CONFFILE"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Main application
-
+# options
+SETARGS="$*"
+SHORTOPTS="a,l,c,v,h"
+LONGOPTS="all,list,config,version,help"
+ARRAY=""
+setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -n "$PROG" -- "$@" 2>/dev/null)
+eval set -- "$setopts" 2>/dev/null
+while :; do
+  case $1 in
+  -a | --all) __list_options ;;
+  -l | --list) __list_array ;;
+  -v | --version) __version ;;
+  -h | --help) __help ;;
+  -c | --config) __gen_config ;;
+  --)
+    shift 1
+    break
+    ;;
+    #*) break ;;
+  esac
+  shift
+done
+set -- "$SETARGS"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Required app check
+cmd_exists --error bash || exit 1
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# begin main app
+case ${ARRAY:-$1} in
+*) printf_green "Version:$VERSION DIR=$GEN_SCRIPTS_REPLACE_CONFDIR" ;;
+esac
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# End application
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit $?
-# end
