🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/templates/scripts/bash/case b/templates/scripts/bash/case
--- a/templates/scripts/bash/case
+++ b/templates/scripts/bash/case
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-PROG="REPLACE_FILENAME"
+PROG="GEN_SCRIPT_GEN_SCRIPT_REPLACE_FILENAME"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
@@ -8,17 +8,18 @@ SRC_DIR="${BASH_SOURCE%/*}"
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : REPLACE_VERSION
-# @Author        : REPLACE_AUTHOR
-# @Contact       : REPLACE_EMAIL
-# @License       : REPLACE_LICENSE
-# @Copyright     : REPLACE_COPYRIGHT
-# @Created       : REPLACE_DATE
-# @File          : REPLACE_FILENAME
-# @Description   : REPLACE_DESC
-# @TODO          : REPLACE_TODO
-# @Other         : REPLACE_OTHER
-# @Resource      : REPLACE_RES
+##@Version       : GEN_SCRIPT_GEN_SCRIPT_REPLACE_VERSION
+# @Author        : GEN_SCRIPT_GEN_SCRIPT_REPLACE_AUTHOR
+# @Contact       : GEN_SCRIPT_GEN_SCRIPT_REPLACE_EMAIL
+# @License       : GEN_SCRIPT_GEN_SCRIPT_REPLACE_LICENSE
+# @ReadME        : GEN_SCRIPT_GEN_SCRIPT_REPLACE_FILENAME --help
+# @Copyright     : GEN_SCRIPT_GEN_SCRIPT_REPLACE_COPYRIGHT
+# @Created       : GEN_SCRIPT_GEN_SCRIPT_REPLACE_DATE
+# @File          : GEN_SCRIPT_GEN_SCRIPT_REPLACE_FILENAME
+# @Description   : GEN_SCRIPT_GEN_SCRIPT_REPLACE_DESC
+# @TODO          : GEN_SCRIPT_GEN_SCRIPT_REPLACE_TODO
+# @Other         : GEN_SCRIPT_GEN_SCRIPT_REPLACE_OTHER
+# @Resource      : GEN_SCRIPT_GEN_SCRIPT_REPLACE_RES
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Import functions
 CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
@@ -52,11 +53,11 @@ __cmd_exists bash || exit 1 # exit 1 if not found
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # bring in user config
-[ -f "$HOME/.config/REPLACE_FILENAME/settings" ] && . "$HOME/.config/REPLACE_FILENAME/settings"
+[ -f "$HOME/.config/GEN_SCRIPT_GEN_SCRIPT_REPLACE_FILENAME/settings" ] && . "$HOME/.config/GEN_SCRIPT_GEN_SCRIPT_REPLACE_FILENAME/settings"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Set up the case statements
-t=$(getopt -o h,v,c,t:,n: --long help,version,config,title:,name: -n "REPLACE_FILENAME" -- "$@") # get options
-eval set -- "$t"                                                                                 # set
+t=$(getopt -o h,v,c,t:,n: --long help,version,config,title:,name: -n "GEN_SCRIPT_GEN_SCRIPT_REPLACE_FILENAME" -- "$@") # get options
+eval set -- "$t"                                                                                                       # set
 
 while :; do
   case "$1" in
@@ -82,7 +83,7 @@ while :; do
     break
     ;;
   *)
-    echo >&2 "REPLACE_FILENAME: Internal error: [$1] not recognized!"
+    echo >&2 "GEN_SCRIPT_GEN_SCRIPT_REPLACE_FILENAME: Internal error: [$1] not recognized!"
     exit 1
     ;;
   esac
@@ -98,4 +99,3 @@ esac
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 exit $?
 # end
-
